// Generated by CIRCT firtool-1.40.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module DCacheDataArray(
  input          clock,
                 io_req_valid,	// src/main/scala/rocket/DCache.scala:42:14
  input  [15:0]  io_req_bits_addr,	// src/main/scala/rocket/DCache.scala:42:14
  input          io_req_bits_write,	// src/main/scala/rocket/DCache.scala:42:14
  input  [511:0] io_req_bits_wdata,	// src/main/scala/rocket/DCache.scala:42:14
  input  [15:0]  io_req_bits_wordMask,	// src/main/scala/rocket/DCache.scala:42:14
  input  [3:0]   io_req_bits_eccMask,	// src/main/scala/rocket/DCache.scala:42:14
  output [511:0] io_resp_0	// src/main/scala/rocket/DCache.scala:42:14
);

  wire         data_arrays_15_rdata_data_15_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_15_rdata_MPORT_15_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_14_rdata_data_14_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_14_rdata_MPORT_14_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_13_rdata_data_13_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_13_rdata_MPORT_13_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_12_rdata_data_12_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_12_rdata_MPORT_12_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_11_rdata_data_11_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_11_rdata_MPORT_11_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_10_rdata_data_10_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_10_rdata_MPORT_10_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_9_rdata_data_9_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_9_rdata_MPORT_9_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_8_rdata_data_8_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_8_rdata_MPORT_8_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_7_rdata_data_7_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_7_rdata_MPORT_7_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_6_rdata_data_6_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_6_rdata_MPORT_6_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_5_rdata_data_5_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_5_rdata_MPORT_5_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_4_rdata_data_4_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_4_rdata_MPORT_4_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_3_rdata_data_3_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_3_rdata_MPORT_3_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_2_rdata_data_2_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_2_rdata_MPORT_2_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_1_rdata_data_1_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_1_rdata_MPORT_1_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire         data_arrays_0_rdata_data_en;	// src/main/scala/rocket/DCache.scala:69:39
  wire         data_arrays_0_rdata_MPORT_en;	// src/main/scala/rocket/DCache.scala:64:17
  wire [31:0]  _data_arrays_15_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_14_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_13_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_12_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_11_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_10_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_9_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_8_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_7_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_6_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_5_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_4_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_3_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_2_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_1_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire [31:0]  _data_arrays_0_ext_RW0_rdata;	// src/main/scala/util/DescribedSRAM.scala:17:26
  wire         eccMask_0 = io_req_bits_eccMask[0];	// src/main/scala/rocket/DCache.scala:48:82
  wire         eccMask_1 = io_req_bits_eccMask[1];	// src/main/scala/rocket/DCache.scala:48:82
  wire         eccMask_2 = io_req_bits_eccMask[2];	// src/main/scala/rocket/DCache.scala:48:82
  wire         eccMask_3 = io_req_bits_eccMask[3];	// src/main/scala/rocket/DCache.scala:48:82
  wire [31:0]  wWords_0 = io_req_bits_wdata[31:0];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_1 = io_req_bits_wdata[63:32];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_2 = io_req_bits_wdata[95:64];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_3 = io_req_bits_wdata[127:96];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_4 = io_req_bits_wdata[159:128];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_5 = io_req_bits_wdata[191:160];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_6 = io_req_bits_wdata[223:192];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_7 = io_req_bits_wdata[255:224];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_8 = io_req_bits_wdata[287:256];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_9 = io_req_bits_wdata[319:288];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_10 = io_req_bits_wdata[351:320];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_11 = io_req_bits_wdata[383:352];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_12 = io_req_bits_wdata[415:384];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_13 = io_req_bits_wdata[447:416];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_14 = io_req_bits_wdata[479:448];	// src/main/scala/util/package.scala:211:50
  wire [31:0]  wWords_15 = io_req_bits_wdata[511:480];	// src/main/scala/util/package.scala:211:50
  wire [9:0]   addr = io_req_bits_addr[15:6];	// src/main/scala/rocket/DCache.scala:51:31
  wire [7:0]   rdata_wData_0;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3;	// src/main/scala/util/package.scala:211:50
  wire [3:0]   _GEN = {eccMask_3, eccMask_2, eccMask_1, eccMask_0};	// src/main/scala/rocket/DCache.scala:48:82, src/main/scala/util/DescribedSRAM.scala:17:26
  wire [7:0]   rdata_wData_0_1;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_1;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_1;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_1;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_2;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_2;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_2;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_2;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_3;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_3;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_3;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_3;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_4;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_4;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_4;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_4;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_5;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_5;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_5;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_5;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_6;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_6;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_6;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_6;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_7;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_7;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_7;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_7;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_8;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_8;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_8;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_8;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_9;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_9;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_9;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_9;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_10;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_10;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_10;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_10;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_11;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_11;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_11;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_11;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_12;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_12;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_12;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_12;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_13;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_13;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_13;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_13;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_14;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_14;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_14;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_14;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_0_15;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_1_15;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_2_15;	// src/main/scala/util/package.scala:211:50
  wire [7:0]   rdata_wData_3_15;	// src/main/scala/util/package.scala:211:50
  wire         rdata_valid = io_req_valid & io_req_bits_wordMask[0];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_0_rdata_MPORT_en = rdata_valid & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0 = wWords_0[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1 = wWords_0[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2 = wWords_0[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3 = wWords_0[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_0_rdata_data_en = rdata_valid & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo = _data_arrays_0_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi = _data_arrays_0_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_0_0 = {rdata_hi, rdata_lo};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_1 = io_req_valid & io_req_bits_wordMask[1];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_1_rdata_MPORT_1_en = rdata_valid_1 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_1 = wWords_1[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_1 = wWords_1[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_1 = wWords_1[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_1 = wWords_1[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_1_rdata_data_1_en = rdata_valid_1 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_1 = _data_arrays_1_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_1 = _data_arrays_1_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_1_0 = {rdata_hi_1, rdata_lo_1};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_2 = io_req_valid & io_req_bits_wordMask[2];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_2_rdata_MPORT_2_en = rdata_valid_2 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_2 = wWords_2[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_2 = wWords_2[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_2 = wWords_2[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_2 = wWords_2[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_2_rdata_data_2_en = rdata_valid_2 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_2 = _data_arrays_2_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_2 = _data_arrays_2_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_2_0 = {rdata_hi_2, rdata_lo_2};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_3 = io_req_valid & io_req_bits_wordMask[3];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_3_rdata_MPORT_3_en = rdata_valid_3 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_3 = wWords_3[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_3 = wWords_3[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_3 = wWords_3[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_3 = wWords_3[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_3_rdata_data_3_en = rdata_valid_3 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_3 = _data_arrays_3_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_3 = _data_arrays_3_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_3_0 = {rdata_hi_3, rdata_lo_3};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_4 = io_req_valid & io_req_bits_wordMask[4];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_4_rdata_MPORT_4_en = rdata_valid_4 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_4 = wWords_4[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_4 = wWords_4[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_4 = wWords_4[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_4 = wWords_4[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_4_rdata_data_4_en = rdata_valid_4 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_4 = _data_arrays_4_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_4 = _data_arrays_4_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_4_0 = {rdata_hi_4, rdata_lo_4};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_5 = io_req_valid & io_req_bits_wordMask[5];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_5_rdata_MPORT_5_en = rdata_valid_5 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_5 = wWords_5[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_5 = wWords_5[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_5 = wWords_5[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_5 = wWords_5[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_5_rdata_data_5_en = rdata_valid_5 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_5 = _data_arrays_5_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_5 = _data_arrays_5_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_5_0 = {rdata_hi_5, rdata_lo_5};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_6 = io_req_valid & io_req_bits_wordMask[6];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_6_rdata_MPORT_6_en = rdata_valid_6 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_6 = wWords_6[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_6 = wWords_6[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_6 = wWords_6[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_6 = wWords_6[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_6_rdata_data_6_en = rdata_valid_6 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_6 = _data_arrays_6_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_6 = _data_arrays_6_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_6_0 = {rdata_hi_6, rdata_lo_6};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_7 = io_req_valid & io_req_bits_wordMask[7];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_7_rdata_MPORT_7_en = rdata_valid_7 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_7 = wWords_7[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_7 = wWords_7[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_7 = wWords_7[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_7 = wWords_7[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_7_rdata_data_7_en = rdata_valid_7 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_7 = _data_arrays_7_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_7 = _data_arrays_7_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_7_0 = {rdata_hi_7, rdata_lo_7};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_8 = io_req_valid & io_req_bits_wordMask[8];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_8_rdata_MPORT_8_en = rdata_valid_8 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_8 = wWords_8[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_8 = wWords_8[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_8 = wWords_8[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_8 = wWords_8[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_8_rdata_data_8_en = rdata_valid_8 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_8 = _data_arrays_8_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_8 = _data_arrays_8_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_8_0 = {rdata_hi_8, rdata_lo_8};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_9 = io_req_valid & io_req_bits_wordMask[9];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_9_rdata_MPORT_9_en = rdata_valid_9 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_9 = wWords_9[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_9 = wWords_9[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_9 = wWords_9[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_9 = wWords_9[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_9_rdata_data_9_en = rdata_valid_9 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_9 = _data_arrays_9_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_9 = _data_arrays_9_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_9_0 = {rdata_hi_9, rdata_lo_9};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_10 = io_req_valid & io_req_bits_wordMask[10];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_10_rdata_MPORT_10_en = rdata_valid_10 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_10 = wWords_10[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_10 = wWords_10[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_10 = wWords_10[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_10 = wWords_10[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_10_rdata_data_10_en = rdata_valid_10 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_10 = _data_arrays_10_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_10 = _data_arrays_10_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_10_0 = {rdata_hi_10, rdata_lo_10};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_11 = io_req_valid & io_req_bits_wordMask[11];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_11_rdata_MPORT_11_en = rdata_valid_11 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_11 = wWords_11[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_11 = wWords_11[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_11 = wWords_11[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_11 = wWords_11[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_11_rdata_data_11_en = rdata_valid_11 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_11 = _data_arrays_11_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_11 = _data_arrays_11_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_11_0 = {rdata_hi_11, rdata_lo_11};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_12 = io_req_valid & io_req_bits_wordMask[12];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_12_rdata_MPORT_12_en = rdata_valid_12 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_12 = wWords_12[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_12 = wWords_12[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_12 = wWords_12[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_12 = wWords_12[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_12_rdata_data_12_en = rdata_valid_12 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_12 = _data_arrays_12_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_12 = _data_arrays_12_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_12_0 = {rdata_hi_12, rdata_lo_12};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_13 = io_req_valid & io_req_bits_wordMask[13];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_13_rdata_MPORT_13_en = rdata_valid_13 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_13 = wWords_13[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_13 = wWords_13[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_13 = wWords_13[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_13 = wWords_13[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_13_rdata_data_13_en = rdata_valid_13 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_13 = _data_arrays_13_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_13 = _data_arrays_13_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_13_0 = {rdata_hi_13, rdata_lo_13};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_14 = io_req_valid & io_req_bits_wordMask[14];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_14_rdata_MPORT_14_en = rdata_valid_14 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_14 = wWords_14[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_14 = wWords_14[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_14 = wWords_14[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_14 = wWords_14[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_14_rdata_data_14_en = rdata_valid_14 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_14 = _data_arrays_14_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_14 = _data_arrays_14_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_14_0 = {rdata_hi_14, rdata_lo_14};	// src/main/scala/util/package.scala:45:27
  wire         rdata_valid_15 = io_req_valid & io_req_bits_wordMask[15];	// src/main/scala/rocket/DCache.scala:63:{30,83}
  assign data_arrays_15_rdata_MPORT_15_en = rdata_valid_15 & io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :64:17
  assign rdata_wData_0_15 = wWords_15[7:0];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_1_15 = wWords_15[15:8];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_2_15 = wWords_15[23:16];	// src/main/scala/util/package.scala:211:50
  assign rdata_wData_3_15 = wWords_15[31:24];	// src/main/scala/util/package.scala:211:50
  assign data_arrays_15_rdata_data_15_en = rdata_valid_15 & ~io_req_bits_write;	// src/main/scala/rocket/DCache.scala:63:30, :69:{39,42}
  wire [15:0]  rdata_lo_15 = _data_arrays_15_ext_RW0_rdata[15:0];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [15:0]  rdata_hi_15 = _data_arrays_15_ext_RW0_rdata[31:16];	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:45:27
  wire [31:0]  rdata_15_0 = {rdata_hi_15, rdata_lo_15};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_lo_lo_lo = {rdata_1_0, rdata_0_0};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_lo_lo_hi = {rdata_3_0, rdata_2_0};	// src/main/scala/util/package.scala:45:27
  wire [127:0] io_resp_0_lo_lo = {io_resp_0_lo_lo_hi, io_resp_0_lo_lo_lo};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_lo_hi_lo = {rdata_5_0, rdata_4_0};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_lo_hi_hi = {rdata_7_0, rdata_6_0};	// src/main/scala/util/package.scala:45:27
  wire [127:0] io_resp_0_lo_hi = {io_resp_0_lo_hi_hi, io_resp_0_lo_hi_lo};	// src/main/scala/util/package.scala:45:27
  wire [255:0] io_resp_0_lo = {io_resp_0_lo_hi, io_resp_0_lo_lo};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_hi_lo_lo = {rdata_9_0, rdata_8_0};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_hi_lo_hi = {rdata_11_0, rdata_10_0};	// src/main/scala/util/package.scala:45:27
  wire [127:0] io_resp_0_hi_lo = {io_resp_0_hi_lo_hi, io_resp_0_hi_lo_lo};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_hi_hi_lo = {rdata_13_0, rdata_12_0};	// src/main/scala/util/package.scala:45:27
  wire [63:0]  io_resp_0_hi_hi_hi = {rdata_15_0, rdata_14_0};	// src/main/scala/util/package.scala:45:27
  wire [127:0] io_resp_0_hi_hi = {io_resp_0_hi_hi_hi, io_resp_0_hi_hi_lo};	// src/main/scala/util/package.scala:45:27
  wire [255:0] io_resp_0_hi = {io_resp_0_hi_hi, io_resp_0_hi_lo};	// src/main/scala/util/package.scala:45:27
  data_arrays_0_combMem data_arrays_0_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_0_rdata_data_en | data_arrays_0_rdata_MPORT_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3, rdata_wData_2, rdata_wData_1, rdata_wData_0}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_0_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_1_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_1_rdata_data_1_en | data_arrays_1_rdata_MPORT_1_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_1, rdata_wData_2_1, rdata_wData_1_1, rdata_wData_0_1}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_1_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_2_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_2_rdata_data_2_en | data_arrays_2_rdata_MPORT_2_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_2, rdata_wData_2_2, rdata_wData_1_2, rdata_wData_0_2}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_2_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_3_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_3_rdata_data_3_en | data_arrays_3_rdata_MPORT_3_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_3, rdata_wData_2_3, rdata_wData_1_3, rdata_wData_0_3}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_3_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_4_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_4_rdata_data_4_en | data_arrays_4_rdata_MPORT_4_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_4, rdata_wData_2_4, rdata_wData_1_4, rdata_wData_0_4}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_4_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_5_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_5_rdata_data_5_en | data_arrays_5_rdata_MPORT_5_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_5, rdata_wData_2_5, rdata_wData_1_5, rdata_wData_0_5}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_5_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_6_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_6_rdata_data_6_en | data_arrays_6_rdata_MPORT_6_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_6, rdata_wData_2_6, rdata_wData_1_6, rdata_wData_0_6}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_6_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_7_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_7_rdata_data_7_en | data_arrays_7_rdata_MPORT_7_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_7, rdata_wData_2_7, rdata_wData_1_7, rdata_wData_0_7}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_7_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_8_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_8_rdata_data_8_en | data_arrays_8_rdata_MPORT_8_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_8, rdata_wData_2_8, rdata_wData_1_8, rdata_wData_0_8}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_8_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_9_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_9_rdata_data_9_en | data_arrays_9_rdata_MPORT_9_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_9, rdata_wData_2_9, rdata_wData_1_9, rdata_wData_0_9}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_9_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_10_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_10_rdata_data_10_en | data_arrays_10_rdata_MPORT_10_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_10, rdata_wData_2_10, rdata_wData_1_10, rdata_wData_0_10}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_10_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_11_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_11_rdata_data_11_en | data_arrays_11_rdata_MPORT_11_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_11, rdata_wData_2_11, rdata_wData_1_11, rdata_wData_0_11}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_11_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_12_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_12_rdata_data_12_en | data_arrays_12_rdata_MPORT_12_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_12, rdata_wData_2_12, rdata_wData_1_12, rdata_wData_0_12}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_12_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_13_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_13_rdata_data_13_en | data_arrays_13_rdata_MPORT_13_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_13, rdata_wData_2_13, rdata_wData_1_13, rdata_wData_0_13}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_13_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_14_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_14_rdata_data_14_en | data_arrays_14_rdata_MPORT_14_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_14, rdata_wData_2_14, rdata_wData_1_14, rdata_wData_0_14}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_14_ext_RW0_rdata)
  );
  data_arrays_0_combMem data_arrays_15_ext (	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_addr  (addr),	// src/main/scala/rocket/DCache.scala:51:31
    .RW0_en    (data_arrays_15_rdata_data_15_en | data_arrays_15_rdata_MPORT_15_en),	// src/main/scala/rocket/DCache.scala:64:17, :69:39, src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata ({rdata_wData_3_15, rdata_wData_2_15, rdata_wData_1_15, rdata_wData_0_15}),	// src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/util/package.scala:211:50
    .RW0_wmask (_GEN),	// src/main/scala/util/DescribedSRAM.scala:17:26
    .RW0_rdata (_data_arrays_15_ext_RW0_rdata)
  );
  assign io_resp_0 = {io_resp_0_hi, io_resp_0_lo};	// src/main/scala/util/package.scala:45:27
endmodule

