//
// Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
//
// timestamp removed
//
// BVI format method schedule info:
// schedule portalIfc_messageSize_size  CF ( portalIfc_messageSize_size,
// 					  portalIfc_indications_0_first,
// 					  portalIfc_indications_0_deq,
// 					  portalIfc_indications_0_notEmpty,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  ifc_startPC );
//
// schedule portalIfc_indications_0_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_startPC );
// schedule portalIfc_indications_0_first  SB ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_deq  CF ( portalIfc_messageSize_size,
// 					   ifc_startPC );
// schedule portalIfc_indications_0_deq  C ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel );
// schedule portalIfc_indications_0_notEmpty  SB ( portalIfc_indications_0_deq,
// 						ifc_startPC );
//
// schedule portalIfc_intr_status  CF ( portalIfc_messageSize_size,
// 				     portalIfc_indications_0_first,
// 				     portalIfc_indications_0_notEmpty,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel );
// schedule portalIfc_intr_status  SB ( portalIfc_indications_0_deq,
// 				     ifc_startPC );
//
// schedule portalIfc_intr_channel  CF ( portalIfc_messageSize_size,
// 				      portalIfc_indications_0_first,
// 				      portalIfc_indications_0_notEmpty,
// 				      portalIfc_intr_status,
// 				      portalIfc_intr_channel );
// schedule portalIfc_intr_channel  SB ( portalIfc_indications_0_deq,
// 				      ifc_startPC );
//
// schedule ifc_startPC  CF ( portalIfc_messageSize_size,
// 			   portalIfc_indications_0_first,
// 			   portalIfc_indications_0_deq );
// schedule ifc_startPC  C ( ifc_startPC );
//
//
// Ports:
// Name                         I/O  size props
// portalIfc_messageSize_size     O    16 const
// RDY_portalIfc_messageSize_size  O     1 const
// portalIfc_indications_0_first  O    32 reg
// RDY_portalIfc_indications_0_first  O     1 reg
// RDY_portalIfc_indications_0_deq  O     1 reg
// portalIfc_indications_0_notEmpty  O     1 reg
// RDY_portalIfc_indications_0_notEmpty  O     1 const
// portalIfc_intr_status          O     1 reg
// RDY_portalIfc_intr_status      O     1 const
// portalIfc_intr_channel         O    32
// RDY_portalIfc_intr_channel     O     1 const
// RDY_ifc_startPC                O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// portalIfc_messageSize_size_methodNumber  I    16 unused
// ifc_startPC_pc                 I    32 reg
// EN_portalIfc_indications_0_deq  I     1
// EN_ifc_startPC                 I     1
//
// Combinational paths from inputs to outputs:
//   portalIfc_messageSize_size_methodNumber -> portalIfc_messageSize_size
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFromHostOutput(CLK,
			RST_N,

			portalIfc_messageSize_size_methodNumber,
			portalIfc_messageSize_size,
			RDY_portalIfc_messageSize_size,

			portalIfc_indications_0_first,
			RDY_portalIfc_indications_0_first,

			EN_portalIfc_indications_0_deq,
			RDY_portalIfc_indications_0_deq,

			portalIfc_indications_0_notEmpty,
			RDY_portalIfc_indications_0_notEmpty,

			portalIfc_intr_status,
			RDY_portalIfc_intr_status,

			portalIfc_intr_channel,
			RDY_portalIfc_intr_channel,

			ifc_startPC_pc,
			EN_ifc_startPC,
			RDY_ifc_startPC);
  input  CLK;
  input  RST_N;

  // value method portalIfc_messageSize_size
  input  [15 : 0] portalIfc_messageSize_size_methodNumber;
  output [15 : 0] portalIfc_messageSize_size;
  output RDY_portalIfc_messageSize_size;

  // value method portalIfc_indications_0_first
  output [31 : 0] portalIfc_indications_0_first;
  output RDY_portalIfc_indications_0_first;

  // action method portalIfc_indications_0_deq
  input  EN_portalIfc_indications_0_deq;
  output RDY_portalIfc_indications_0_deq;

  // value method portalIfc_indications_0_notEmpty
  output portalIfc_indications_0_notEmpty;
  output RDY_portalIfc_indications_0_notEmpty;

  // value method portalIfc_intr_status
  output portalIfc_intr_status;
  output RDY_portalIfc_intr_status;

  // value method portalIfc_intr_channel
  output [31 : 0] portalIfc_intr_channel;
  output RDY_portalIfc_intr_channel;

  // action method ifc_startPC
  input  [31 : 0] ifc_startPC_pc;
  input  EN_ifc_startPC;
  output RDY_ifc_startPC;

  // signals for module outputs
  wire [31 : 0] portalIfc_indications_0_first, portalIfc_intr_channel;
  wire [15 : 0] portalIfc_messageSize_size;
  wire RDY_ifc_startPC,
       RDY_portalIfc_indications_0_deq,
       RDY_portalIfc_indications_0_first,
       RDY_portalIfc_indications_0_notEmpty,
       RDY_portalIfc_intr_channel,
       RDY_portalIfc_intr_status,
       RDY_portalIfc_messageSize_size,
       portalIfc_indications_0_notEmpty,
       portalIfc_intr_status;

  // ports of submodule indicationPipes
  wire [31 : 0] indicationPipes_methods_startPC_enq_v,
		indicationPipes_portalIfc_indications_0_first,
		indicationPipes_portalIfc_intr_channel;
  wire [15 : 0] indicationPipes_portalIfc_messageSize_size,
		indicationPipes_portalIfc_messageSize_size_methodNumber;
  wire indicationPipes_EN_methods_startPC_enq,
       indicationPipes_EN_portalIfc_indications_0_deq,
       indicationPipes_RDY_methods_startPC_enq,
       indicationPipes_RDY_portalIfc_indications_0_deq,
       indicationPipes_RDY_portalIfc_indications_0_first,
       indicationPipes_portalIfc_indications_0_notEmpty,
       indicationPipes_portalIfc_intr_status;

  // value method portalIfc_messageSize_size
  assign portalIfc_messageSize_size =
	     indicationPipes_portalIfc_messageSize_size ;
  assign RDY_portalIfc_messageSize_size = 1'd1 ;

  // value method portalIfc_indications_0_first
  assign portalIfc_indications_0_first =
	     indicationPipes_portalIfc_indications_0_first ;
  assign RDY_portalIfc_indications_0_first =
	     indicationPipes_RDY_portalIfc_indications_0_first ;

  // action method portalIfc_indications_0_deq
  assign RDY_portalIfc_indications_0_deq =
	     indicationPipes_RDY_portalIfc_indications_0_deq ;

  // value method portalIfc_indications_0_notEmpty
  assign portalIfc_indications_0_notEmpty =
	     indicationPipes_portalIfc_indications_0_notEmpty ;
  assign RDY_portalIfc_indications_0_notEmpty = 1'd1 ;

  // value method portalIfc_intr_status
  assign portalIfc_intr_status = indicationPipes_portalIfc_intr_status ;
  assign RDY_portalIfc_intr_status = 1'd1 ;

  // value method portalIfc_intr_channel
  assign portalIfc_intr_channel = indicationPipes_portalIfc_intr_channel ;
  assign RDY_portalIfc_intr_channel = 1'd1 ;

  // action method ifc_startPC
  assign RDY_ifc_startPC = indicationPipes_RDY_methods_startPC_enq ;

  // submodule indicationPipes
  mkFromHostOutputPipes indicationPipes(.CLK(CLK),
					.RST_N(RST_N),
					.methods_startPC_enq_v(indicationPipes_methods_startPC_enq_v),
					.portalIfc_messageSize_size_methodNumber(indicationPipes_portalIfc_messageSize_size_methodNumber),
					.EN_methods_startPC_enq(indicationPipes_EN_methods_startPC_enq),
					.EN_portalIfc_indications_0_deq(indicationPipes_EN_portalIfc_indications_0_deq),
					.RDY_methods_startPC_enq(indicationPipes_RDY_methods_startPC_enq),
					.methods_startPC_notFull(),
					.RDY_methods_startPC_notFull(),
					.portalIfc_messageSize_size(indicationPipes_portalIfc_messageSize_size),
					.RDY_portalIfc_messageSize_size(),
					.portalIfc_indications_0_first(indicationPipes_portalIfc_indications_0_first),
					.RDY_portalIfc_indications_0_first(indicationPipes_RDY_portalIfc_indications_0_first),
					.RDY_portalIfc_indications_0_deq(indicationPipes_RDY_portalIfc_indications_0_deq),
					.portalIfc_indications_0_notEmpty(indicationPipes_portalIfc_indications_0_notEmpty),
					.RDY_portalIfc_indications_0_notEmpty(),
					.portalIfc_intr_status(indicationPipes_portalIfc_intr_status),
					.RDY_portalIfc_intr_status(),
					.portalIfc_intr_channel(indicationPipes_portalIfc_intr_channel),
					.RDY_portalIfc_intr_channel());

  // submodule indicationPipes
  assign indicationPipes_methods_startPC_enq_v = ifc_startPC_pc ;
  assign indicationPipes_portalIfc_messageSize_size_methodNumber =
	     portalIfc_messageSize_size_methodNumber ;
  assign indicationPipes_EN_methods_startPC_enq = EN_ifc_startPC ;
  assign indicationPipes_EN_portalIfc_indications_0_deq =
	     EN_portalIfc_indications_0_deq ;
endmodule  // mkFromHostOutput

