//
// Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
//
// On Mon Sep 19 12:52:32 EDT 2022
//
// BVI format method schedule info:
// schedule portalIfc_messageSize_size  CF ( portalIfc_messageSize_size,
// 					  portalIfc_requests_0_enq,
// 					  portalIfc_requests_0_notFull,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  pipes_print_PipeOut_first,
// 					  pipes_print_PipeOut_deq,
// 					  pipes_print_PipeOut_notEmpty );
//
// schedule portalIfc_requests_0_enq  CF ( portalIfc_messageSize_size,
// 					portalIfc_intr_status,
// 					portalIfc_intr_channel,
// 					pipes_print_PipeOut_first );
// schedule portalIfc_requests_0_enq  SB ( pipes_print_PipeOut_deq );
// schedule portalIfc_requests_0_enq  C ( portalIfc_requests_0_enq );
//
// schedule portalIfc_requests_0_notFull  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_print_PipeOut_first,
// 					    pipes_print_PipeOut_notEmpty );
// schedule portalIfc_requests_0_notFull  SB ( portalIfc_requests_0_enq,
// 					    pipes_print_PipeOut_deq );
//
// schedule portalIfc_intr_status  CF ( portalIfc_messageSize_size,
// 				     portalIfc_requests_0_enq,
// 				     portalIfc_requests_0_notFull,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel,
// 				     pipes_print_PipeOut_first,
// 				     pipes_print_PipeOut_deq,
// 				     pipes_print_PipeOut_notEmpty );
//
// schedule portalIfc_intr_channel  CF ( portalIfc_messageSize_size,
// 				      portalIfc_requests_0_enq,
// 				      portalIfc_requests_0_notFull,
// 				      portalIfc_intr_status,
// 				      portalIfc_intr_channel,
// 				      pipes_print_PipeOut_first,
// 				      pipes_print_PipeOut_deq,
// 				      pipes_print_PipeOut_notEmpty );
//
// schedule pipes_print_PipeOut_first  CF ( portalIfc_messageSize_size,
// 					 portalIfc_requests_0_enq,
// 					 portalIfc_requests_0_notFull,
// 					 portalIfc_intr_status,
// 					 portalIfc_intr_channel,
// 					 pipes_print_PipeOut_first,
// 					 pipes_print_PipeOut_notEmpty );
// schedule pipes_print_PipeOut_first  SB ( pipes_print_PipeOut_deq );
//
// schedule pipes_print_PipeOut_deq  CF ( portalIfc_messageSize_size,
// 				       portalIfc_intr_status,
// 				       portalIfc_intr_channel );
// schedule pipes_print_PipeOut_deq  C ( pipes_print_PipeOut_deq );
//
// schedule pipes_print_PipeOut_notEmpty  CF ( portalIfc_messageSize_size,
// 					    portalIfc_requests_0_notFull,
// 					    portalIfc_intr_status,
// 					    portalIfc_intr_channel,
// 					    pipes_print_PipeOut_first,
// 					    pipes_print_PipeOut_notEmpty );
// schedule pipes_print_PipeOut_notEmpty  SB ( portalIfc_requests_0_enq,
// 					    pipes_print_PipeOut_deq );
//
//
// Ports:
// Name                         I/O  size props
// portalIfc_messageSize_size     O    16 const
// RDY_portalIfc_messageSize_size  O     1 const
// RDY_portalIfc_requests_0_enq   O     1 reg
// portalIfc_requests_0_notFull   O     1 reg
// RDY_portalIfc_requests_0_notFull  O     1 const
// portalIfc_intr_status          O     1 const
// RDY_portalIfc_intr_status      O     1 const
// portalIfc_intr_channel         O    32 const
// RDY_portalIfc_intr_channel     O     1 const
// pipes_print_PipeOut_first      O    32 reg
// RDY_pipes_print_PipeOut_first  O     1 reg
// RDY_pipes_print_PipeOut_deq    O     1 reg
// pipes_print_PipeOut_notEmpty   O     1 reg
// RDY_pipes_print_PipeOut_notEmpty  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// portalIfc_messageSize_size_methodNumber  I    16 unused
// portalIfc_requests_0_enq_v     I    32 reg
// EN_portalIfc_requests_0_enq    I     1
// EN_pipes_print_PipeOut_deq     I     1
//
// Combinational paths from inputs to outputs:
//   portalIfc_messageSize_size_methodNumber -> portalIfc_messageSize_size
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkToHostInput(CLK,
		     RST_N,

		     portalIfc_messageSize_size_methodNumber,
		     portalIfc_messageSize_size,
		     RDY_portalIfc_messageSize_size,

		     portalIfc_requests_0_enq_v,
		     EN_portalIfc_requests_0_enq,
		     RDY_portalIfc_requests_0_enq,

		     portalIfc_requests_0_notFull,
		     RDY_portalIfc_requests_0_notFull,

		     portalIfc_intr_status,
		     RDY_portalIfc_intr_status,

		     portalIfc_intr_channel,
		     RDY_portalIfc_intr_channel,

		     pipes_print_PipeOut_first,
		     RDY_pipes_print_PipeOut_first,

		     EN_pipes_print_PipeOut_deq,
		     RDY_pipes_print_PipeOut_deq,

		     pipes_print_PipeOut_notEmpty,
		     RDY_pipes_print_PipeOut_notEmpty);
  input  CLK;
  input  RST_N;

  // value method portalIfc_messageSize_size
  input  [15 : 0] portalIfc_messageSize_size_methodNumber;
  output [15 : 0] portalIfc_messageSize_size;
  output RDY_portalIfc_messageSize_size;

  // action method portalIfc_requests_0_enq
  input  [31 : 0] portalIfc_requests_0_enq_v;
  input  EN_portalIfc_requests_0_enq;
  output RDY_portalIfc_requests_0_enq;

  // value method portalIfc_requests_0_notFull
  output portalIfc_requests_0_notFull;
  output RDY_portalIfc_requests_0_notFull;

  // value method portalIfc_intr_status
  output portalIfc_intr_status;
  output RDY_portalIfc_intr_status;

  // value method portalIfc_intr_channel
  output [31 : 0] portalIfc_intr_channel;
  output RDY_portalIfc_intr_channel;

  // value method pipes_print_PipeOut_first
  output [31 : 0] pipes_print_PipeOut_first;
  output RDY_pipes_print_PipeOut_first;

  // action method pipes_print_PipeOut_deq
  input  EN_pipes_print_PipeOut_deq;
  output RDY_pipes_print_PipeOut_deq;

  // value method pipes_print_PipeOut_notEmpty
  output pipes_print_PipeOut_notEmpty;
  output RDY_pipes_print_PipeOut_notEmpty;

  // signals for module outputs
  wire [31 : 0] pipes_print_PipeOut_first, portalIfc_intr_channel;
  wire [15 : 0] portalIfc_messageSize_size;
  wire RDY_pipes_print_PipeOut_deq,
       RDY_pipes_print_PipeOut_first,
       RDY_pipes_print_PipeOut_notEmpty,
       RDY_portalIfc_intr_channel,
       RDY_portalIfc_intr_status,
       RDY_portalIfc_messageSize_size,
       RDY_portalIfc_requests_0_enq,
       RDY_portalIfc_requests_0_notFull,
       pipes_print_PipeOut_notEmpty,
       portalIfc_intr_status,
       portalIfc_requests_0_notFull;

  // register print_requestAdapter_fbnbuff
  reg [31 : 0] print_requestAdapter_fbnbuff;
  wire [31 : 0] print_requestAdapter_fbnbuff_D_IN;
  wire print_requestAdapter_fbnbuff_EN;

  // ports of submodule print_requestAdapter_fifo
  wire [31 : 0] print_requestAdapter_fifo_D_IN,
		print_requestAdapter_fifo_D_OUT;
  wire print_requestAdapter_fifo_CLR,
       print_requestAdapter_fifo_DEQ,
       print_requestAdapter_fifo_EMPTY_N,
       print_requestAdapter_fifo_ENQ,
       print_requestAdapter_fifo_FULL_N;

  // value method portalIfc_messageSize_size
  assign portalIfc_messageSize_size = 16'd32 ;
  assign RDY_portalIfc_messageSize_size = 1'd1 ;

  // action method portalIfc_requests_0_enq
  assign RDY_portalIfc_requests_0_enq = print_requestAdapter_fifo_FULL_N ;

  // value method portalIfc_requests_0_notFull
  assign portalIfc_requests_0_notFull = print_requestAdapter_fifo_FULL_N ;
  assign RDY_portalIfc_requests_0_notFull = 1'd1 ;

  // value method portalIfc_intr_status
  assign portalIfc_intr_status = 1'd0 ;
  assign RDY_portalIfc_intr_status = 1'd1 ;

  // value method portalIfc_intr_channel
  assign portalIfc_intr_channel = 32'hFFFFFFFF ;
  assign RDY_portalIfc_intr_channel = 1'd1 ;

  // value method pipes_print_PipeOut_first
  assign pipes_print_PipeOut_first = print_requestAdapter_fifo_D_OUT ;
  assign RDY_pipes_print_PipeOut_first = print_requestAdapter_fifo_EMPTY_N ;

  // action method pipes_print_PipeOut_deq
  assign RDY_pipes_print_PipeOut_deq = print_requestAdapter_fifo_EMPTY_N ;

  // value method pipes_print_PipeOut_notEmpty
  assign pipes_print_PipeOut_notEmpty = print_requestAdapter_fifo_EMPTY_N ;
  assign RDY_pipes_print_PipeOut_notEmpty = 1'd1 ;

  // submodule print_requestAdapter_fifo
  FIFO1 #(.width(32'd32),
	  .guarded(1'd1)) print_requestAdapter_fifo(.RST(RST_N),
						    .CLK(CLK),
						    .D_IN(print_requestAdapter_fifo_D_IN),
						    .ENQ(print_requestAdapter_fifo_ENQ),
						    .DEQ(print_requestAdapter_fifo_DEQ),
						    .CLR(print_requestAdapter_fifo_CLR),
						    .D_OUT(print_requestAdapter_fifo_D_OUT),
						    .FULL_N(print_requestAdapter_fifo_FULL_N),
						    .EMPTY_N(print_requestAdapter_fifo_EMPTY_N));

  // register print_requestAdapter_fbnbuff
  assign print_requestAdapter_fbnbuff_D_IN = portalIfc_requests_0_enq_v ;
  assign print_requestAdapter_fbnbuff_EN = EN_portalIfc_requests_0_enq ;

  // submodule print_requestAdapter_fifo
  assign print_requestAdapter_fifo_D_IN = portalIfc_requests_0_enq_v ;
  assign print_requestAdapter_fifo_ENQ = EN_portalIfc_requests_0_enq ;
  assign print_requestAdapter_fifo_DEQ = EN_pipes_print_PipeOut_deq ;
  assign print_requestAdapter_fifo_CLR = 1'b0 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        print_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (print_requestAdapter_fbnbuff_EN)
	  print_requestAdapter_fbnbuff <= `BSV_ASSIGNMENT_DELAY
	      print_requestAdapter_fbnbuff_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    print_requestAdapter_fbnbuff = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkToHostInput

