// Generated by CIRCT firtool-1.40.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module Frontend(
  input          clock,
                 reset,
                 auto_icache_master_out_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_icache_master_out_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [2:0]   auto_icache_master_out_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [1:0]   auto_icache_master_out_d_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [3:0]   auto_icache_master_out_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [1:0]   auto_icache_master_out_d_bits_sink,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input          auto_icache_master_out_d_bits_denied,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [511:0] auto_icache_master_out_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input          auto_icache_master_out_d_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 io_cpu_might_request,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_req_valid,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_cpu_req_bits_pc,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_cpu_req_bits_speculative,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_sfence_valid,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_resp_ready,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_btb_update_valid,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_cpu_btb_update_bits_prediction_cfiType,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_cpu_btb_update_bits_prediction_taken,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_cpu_btb_update_bits_prediction_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_cpu_btb_update_bits_prediction_bridx,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_cpu_btb_update_bits_prediction_target,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [4:0]   io_cpu_btb_update_bits_prediction_entry,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [7:0]   io_cpu_btb_update_bits_prediction_bht_history,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_cpu_btb_update_bits_prediction_bht_value,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_cpu_btb_update_bits_pc,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_btb_update_bits_target,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_cpu_btb_update_bits_isValid,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_cpu_btb_update_bits_br_pc,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_cpu_btb_update_bits_cfiType,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_cpu_bht_update_valid,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [7:0]   io_cpu_bht_update_bits_prediction_history,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_cpu_bht_update_bits_pc,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_cpu_bht_update_bits_branch,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_bht_update_bits_taken,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_bht_update_bits_mispredict,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_flush_icache,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_progress,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_req_ready,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_ae_ptw,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_ae_final,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pf,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_gf,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_hr,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_hw,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_hx,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [43:0]  io_ptw_resp_bits_pte_ppn,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_resp_bits_pte_d,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pte_a,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pte_g,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pte_u,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pte_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pte_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pte_r,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_pte_v,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_resp_bits_gpa_is_pte,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_ptbr_mode,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [8:0]   io_ptw_ptbr_asid,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [21:0]  io_ptw_ptbr_ppn,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_status_debug,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_status_prv,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_status_mxr,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_status_sum,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_0_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_0_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_0_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_0_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_0_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_0_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_0_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_0_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_1_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_1_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_1_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_1_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_1_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_1_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_1_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_1_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_2_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_2_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_2_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_2_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_2_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_2_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_2_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_2_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_3_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_3_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_3_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_3_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_3_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_3_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_3_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_3_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_4_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_4_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_4_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_4_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_4_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_4_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_4_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_4_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_5_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_5_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_5_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_5_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_5_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_5_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_5_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_5_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_6_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_6_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_6_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_6_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_6_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_6_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_6_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_6_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_7_cfg_l,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [1:0]   io_ptw_pmp_7_cfg_res,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_7_cfg_a,	// src/main/scala/rocket/Frontend.scala:81:14
  input          io_ptw_pmp_7_cfg_x,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_7_cfg_w,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_pmp_7_cfg_r,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [29:0]  io_ptw_pmp_7_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  input  [31:0]  io_ptw_pmp_7_mask,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_customCSRs_csrs_0_value,	// src/main/scala/rocket/Frontend.scala:81:14
  output         auto_icache_master_out_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [31:0]  auto_icache_master_out_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output         auto_icache_master_out_a_bits_user_amba_prot_readalloc,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_icache_master_out_a_bits_user_amba_prot_writealloc,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_icache_master_out_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 io_cpu_resp_valid,	// src/main/scala/rocket/Frontend.scala:81:14
  output [1:0]   io_cpu_resp_bits_btb_cfiType,	// src/main/scala/rocket/Frontend.scala:81:14
  output         io_cpu_resp_bits_btb_taken,	// src/main/scala/rocket/Frontend.scala:81:14
  output [1:0]   io_cpu_resp_bits_btb_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  output         io_cpu_resp_bits_btb_bridx,	// src/main/scala/rocket/Frontend.scala:81:14
  output [31:0]  io_cpu_resp_bits_btb_target,	// src/main/scala/rocket/Frontend.scala:81:14
  output [4:0]   io_cpu_resp_bits_btb_entry,	// src/main/scala/rocket/Frontend.scala:81:14
  output [7:0]   io_cpu_resp_bits_btb_bht_history,	// src/main/scala/rocket/Frontend.scala:81:14
  output         io_cpu_resp_bits_btb_bht_value,	// src/main/scala/rocket/Frontend.scala:81:14
  output [31:0]  io_cpu_resp_bits_pc,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_resp_bits_data,	// src/main/scala/rocket/Frontend.scala:81:14
  output [1:0]   io_cpu_resp_bits_mask,	// src/main/scala/rocket/Frontend.scala:81:14
  output         io_cpu_resp_bits_xcpt_pf_inst,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_resp_bits_xcpt_gf_inst,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_resp_bits_xcpt_ae_inst,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_resp_bits_replay,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_cpu_gpa_valid,	// src/main/scala/rocket/Frontend.scala:81:14
  output [31:0]  io_cpu_gpa_bits,	// src/main/scala/rocket/Frontend.scala:81:14
  output         io_ptw_req_valid,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_req_bits_valid,	// src/main/scala/rocket/Frontend.scala:81:14
  output [19:0]  io_ptw_req_bits_bits_addr,	// src/main/scala/rocket/Frontend.scala:81:14
  output         io_ptw_req_bits_bits_need_gpa,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_req_bits_bits_vstage1,	// src/main/scala/rocket/Frontend.scala:81:14
                 io_ptw_req_bits_bits_stage2	// src/main/scala/rocket/Frontend.scala:81:14
);

  wire [1:0]  _GEN;	// src/main/scala/rocket/Frontend.scala:266:25, :270:40
  wire        _fq_io_enq_valid_T_6;	// src/main/scala/rocket/Frontend.scala:180:52
  wire        _btb_io_resp_valid;	// src/main/scala/rocket/Frontend.scala:194:21
  wire [1:0]  _btb_io_resp_bits_cfiType;	// src/main/scala/rocket/Frontend.scala:194:21
  wire        _btb_io_resp_bits_taken;	// src/main/scala/rocket/Frontend.scala:194:21
  wire [1:0]  _btb_io_resp_bits_mask;	// src/main/scala/rocket/Frontend.scala:194:21
  wire        _btb_io_resp_bits_bridx;	// src/main/scala/rocket/Frontend.scala:194:21
  wire [31:0] _btb_io_resp_bits_target;	// src/main/scala/rocket/Frontend.scala:194:21
  wire [4:0]  _btb_io_resp_bits_entry;	// src/main/scala/rocket/Frontend.scala:194:21
  wire [7:0]  _btb_io_resp_bits_bht_history;	// src/main/scala/rocket/Frontend.scala:194:21
  wire        _btb_io_resp_bits_bht_value;	// src/main/scala/rocket/Frontend.scala:194:21
  wire        _btb_io_ras_head_valid;	// src/main/scala/rocket/Frontend.scala:194:21
  wire [31:0] _btb_io_ras_head_bits;	// src/main/scala/rocket/Frontend.scala:194:21
  wire [31:0] _tlb_io_resp_paddr;	// src/main/scala/rocket/Frontend.scala:101:19
  wire [31:0] _tlb_io_resp_gpa;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _tlb_io_resp_pf_ld;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _tlb_io_resp_pf_inst;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _tlb_io_resp_ae_ld;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _tlb_io_resp_ae_inst;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _tlb_io_resp_ma_ld;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _tlb_io_resp_cacheable;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _tlb_io_ptw_req_valid;	// src/main/scala/rocket/Frontend.scala:101:19
  wire        _fq_io_enq_ready;	// src/main/scala/rocket/Frontend.scala:87:64
  wire [4:0]  _fq_io_mask;	// src/main/scala/rocket/Frontend.scala:87:64
  wire        _icache_io_resp_valid;	// src/main/scala/rocket/Frontend.scala:66:26
  wire [31:0] _icache_io_resp_bits_data;	// src/main/scala/rocket/Frontend.scala:66:26
  wire        _icache_io_resp_bits_replay;	// src/main/scala/rocket/Frontend.scala:66:26
  wire        _icache_io_resp_bits_ae;	// src/main/scala/rocket/Frontend.scala:66:26
  wire        taken_rviImm_b0 = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1112:17
  wire        taken_rviImm_b0_1 = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1112:17
  wire        taken_rviImm_b0_2 = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1112:17
  wire        taken_rviImm_b0_3 = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1112:17
  wire        clock_en = 1'h1;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:90:31
  wire [31:0] resetVectorSinkNodeIn = 32'h10040;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  reg         s1_valid;	// src/main/scala/rocket/Frontend.scala:103:21
  reg         s2_valid;	// src/main/scala/rocket/Frontend.scala:104:25
  wire        s0_fq_has_space =
    ~(_fq_io_mask[2]) | ~(_fq_io_mask[3]) & (~s1_valid | ~s2_valid) | ~(_fq_io_mask[4])
    & ~s1_valid & ~s2_valid;	// src/main/scala/rocket/Frontend.scala:87:64, :103:21, :104:25, :106:{5,16}, :107:{6,17,41,45,55,58,70}, :108:{6,17,41}
  wire        s0_valid = io_cpu_req_valid | s0_fq_has_space;	// src/main/scala/rocket/Frontend.scala:107:70, :109:35
  reg  [31:0] s1_pc;	// src/main/scala/rocket/Frontend.scala:111:18
  reg         s1_speculative;	// src/main/scala/rocket/Frontend.scala:112:27
  reg  [31:0] s2_pc;	// src/main/scala/rocket/Frontend.scala:113:22
  reg         s2_btb_resp_valid;	// src/main/scala/rocket/Frontend.scala:114:44
  reg  [1:0]  s2_btb_resp_bits_cfiType;	// src/main/scala/rocket/Frontend.scala:115:29
  reg         s2_btb_resp_bits_taken;	// src/main/scala/rocket/Frontend.scala:115:29
  reg  [1:0]  s2_btb_resp_bits_mask;	// src/main/scala/rocket/Frontend.scala:115:29
  reg         s2_btb_resp_bits_bridx;	// src/main/scala/rocket/Frontend.scala:115:29
  reg  [31:0] s2_btb_resp_bits_target;	// src/main/scala/rocket/Frontend.scala:115:29
  reg  [4:0]  s2_btb_resp_bits_entry;	// src/main/scala/rocket/Frontend.scala:115:29
  reg  [7:0]  s2_btb_resp_bits_bht_history;	// src/main/scala/rocket/Frontend.scala:115:29
  reg         s2_btb_resp_bits_bht_value;	// src/main/scala/rocket/Frontend.scala:115:29
  wire        taken_predict_taken = s2_btb_resp_bits_bht_value;	// src/main/scala/rocket/Frontend.scala:115:29, :249:54
  wire        taken_predict_taken_1 = s2_btb_resp_bits_bht_value;	// src/main/scala/rocket/Frontend.scala:115:29, :249:54
  wire        s2_btb_taken = s2_btb_resp_valid & s2_btb_resp_bits_taken;	// src/main/scala/rocket/Frontend.scala:114:44, :115:29, :116:40
  reg         s2_tlb_resp_miss;	// src/main/scala/rocket/Frontend.scala:117:24
  reg  [31:0] s2_tlb_resp_paddr;	// src/main/scala/rocket/Frontend.scala:117:24
  reg  [31:0] s2_tlb_resp_gpa;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_gpa_is_pte;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_pf_ld;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_pf_st;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_pf_inst;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_gf_ld;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_gf_st;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_gf_inst;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_ae_ld;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_ae_st;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_ae_inst;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_ma_ld;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_ma_st;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_ma_inst;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_cacheable;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_must_alloc;	// src/main/scala/rocket/Frontend.scala:117:24
  reg         s2_tlb_resp_prefetchable;	// src/main/scala/rocket/Frontend.scala:117:24
  wire        s2_xcpt = s2_tlb_resp_ae_inst | s2_tlb_resp_pf_inst | s2_tlb_resp_gf_inst;	// src/main/scala/rocket/Frontend.scala:117:24, :118:60
  reg         s2_speculative;	// src/main/scala/rocket/Frontend.scala:119:31
  reg         s2_partial_insn_valid;	// src/main/scala/rocket/Frontend.scala:120:38
  reg  [15:0] s2_partial_insn;	// src/main/scala/rocket/Frontend.scala:121:28
  reg         wrong_path;	// src/main/scala/rocket/Frontend.scala:122:27
  wire [31:0] s1_base_pc = {s1_pc[31:2], 2'h0};	// src/main/scala/rocket/Frontend.scala:111:18, :124:{20,29}, :153:97
  wire [31:0] ntpc = s1_base_pc + 32'h4;	// src/main/scala/rocket/Frontend.scala:124:20, :125:25
  wire        _T_37 = _fq_io_enq_ready & _fq_io_enq_valid_T_6;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:87:64, :180:52
  reg         s2_replay_REG;	// src/main/scala/rocket/Frontend.scala:130:56
  wire        s2_replay = s2_valid & ~_T_37 | s2_replay_REG;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:104:25, :129:23, :130:{26,29,46,56}
  wire [32:0] predicted_npc;	// src/main/scala/rocket/Frontend.scala:126:34
  wire [32:0] npc = s2_replay ? {1'h0, s2_pc} : predicted_npc;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:113:22, :126:34, :129:23, :131:16
  wire        predicted_taken;	// src/main/scala/rocket/Frontend.scala:127:36
  wire        s0_speculative =
    s1_speculative | s2_valid & ~s2_speculative | predicted_taken;	// src/main/scala/rocket/Frontend.scala:104:25, :112:27, :119:31, :127:36, :137:{53,56,72}
  reg  [1:0]  recent_progress_counter;	// src/main/scala/rocket/Frontend.scala:151:40
  wire        recent_progress = |recent_progress_counter;	// src/main/scala/rocket/Frontend.scala:151:40, :152:49
  wire        s2_kill_speculative_tlb_refill = s2_speculative & ~recent_progress;	// src/main/scala/rocket/Frontend.scala:119:31, :152:49, :156:{55,58}
  wire        s2_redirect;	// src/main/scala/rocket/Frontend.scala:141:32
  wire        s2_can_speculatively_refill =
    s2_tlb_resp_cacheable & ~(io_ptw_customCSRs_csrs_0_value[3]);	// src/main/scala/rocket/Frontend.scala:117:24, :175:{59,62}, src/main/scala/tile/CustomCSRs.scala:46:69
  wire        _icache_io_s2_kill_T_2 =
    s2_speculative & ~s2_can_speculatively_refill | s2_xcpt;	// src/main/scala/rocket/Frontend.scala:118:60, :119:31, :175:59, :176:{39,42,71}
  reg         fq_io_enq_valid_REG;	// src/main/scala/rocket/Frontend.scala:180:29
  wire        _fq_io_enq_bits_replay_T_5 =
    s2_kill_speculative_tlb_refill & s2_tlb_resp_miss;	// src/main/scala/rocket/Frontend.scala:117:24, :156:55, :180:112
  assign _fq_io_enq_valid_T_6 =
    fq_io_enq_valid_REG & s2_valid
    & (_icache_io_resp_valid | _fq_io_enq_bits_replay_T_5 | ~s2_tlb_resp_miss
       & _icache_io_s2_kill_T_2);	// src/main/scala/rocket/Frontend.scala:66:26, :104:25, :117:24, :176:71, :180:{29,52,112,133,137,155}
  wire [31:0] _GEN_0 = {io_cpu_req_valid ? io_cpu_req_bits_pc[31:1] : npc[31:1], 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:131:16, :182:{14,28}
  wire [2:0]  _fq_io_enq_bits_mask_T_1 = 3'h3 << s2_pc[1];	// src/main/scala/rocket/Frontend.scala:113:22, :185:50, src/main/scala/util/package.scala:163:13
  assign predicted_taken = _btb_io_resp_valid & _btb_io_resp_bits_taken;	// src/main/scala/rocket/Frontend.scala:127:36, :194:21, :209:29
  wire [31:0] s2_base_pc = {s2_pc[31:2], 2'h0};	// src/main/scala/rocket/Frontend.scala:113:22, :153:97, :218:{22,31}
  wire        taken_taken;	// src/main/scala/rocket/Frontend.scala:251:71
  wire [31:0] taken_pc = s2_base_pc;	// src/main/scala/rocket/Frontend.scala:218:22, :283:33
  wire        taken_idx = ~taken_taken;	// src/main/scala/rocket/Frontend.scala:219:25, :251:71, :266:13
  wire        fetch_bubble_likely = ~(_fq_io_mask[1]);	// src/main/scala/rocket/Frontend.scala:87:64, :314:{33,44}
  wire        updateBTB;	// src/main/scala/rocket/Frontend.scala:222:32
  wire [1:0]  after_idx;	// src/main/scala/rocket/Frontend.scala:220:25
  wire        taken_prevRVI = s2_partial_insn_valid & (&(s2_partial_insn[1:0]));	// src/main/scala/rocket/Frontend.scala:120:38, :121:28, :229:{39,45}, :230:31
  wire        taken_valid = _fq_io_enq_bits_mask_T_1[0] & ~taken_prevRVI;	// src/main/scala/rocket/Frontend.scala:185:50, :230:31, :231:{38,44,47}
  wire [15:0] taken_bits = _icache_io_resp_bits_data[15:0];	// src/main/scala/rocket/Frontend.scala:66:26, :232:37
  wire        taken_rvc = taken_bits[1:0] != 2'h3;	// src/main/scala/rocket/Frontend.scala:124:29, :229:{39,45}, :232:37
  wire [31:0] taken_rviBits = {taken_bits, s2_partial_insn};	// src/main/scala/rocket/Frontend.scala:121:28, :232:37, :234:24
  wire        taken_rviBranch = taken_rviBits[6:0] == 7'h63;	// src/main/scala/rocket/Frontend.scala:234:24, :235:{30,36}
  wire        taken_rviJump = taken_rviBits[6:0] == 7'h6F;	// src/main/scala/rocket/Frontend.scala:234:24, :235:30, :236:34
  wire        taken_rviJALR = taken_rviBits[6:0] == 7'h67;	// src/main/scala/rocket/Frontend.scala:234:24, :235:30, :237:34
  wire        taken_rviImm_b11_1 = taken_rviBits[7];	// src/main/scala/rocket/Frontend.scala:234:24, :238:42, src/main/scala/rocket/RocketCore.scala:1105:18
  wire        taken_rviReturn =
    taken_rviJALR & ~taken_rviImm_b11_1
    & {taken_rviBits[19:18], taken_rviBits[16:15]} == 4'h1;	// src/main/scala/rocket/Frontend.scala:234:24, :237:34, :238:{34,46,66}, src/main/scala/rocket/RocketCore.scala:1105:18
  wire        _taken_taken_T = taken_rviJALR | taken_rviJump;	// src/main/scala/rocket/Frontend.scala:236:34, :237:34, :239:30
  wire        taken_rviCall = _taken_taken_T & taken_rviImm_b11_1;	// src/main/scala/rocket/Frontend.scala:239:{30,42}, src/main/scala/rocket/RocketCore.scala:1105:18
  wire [4:0]  _GEN_1 = {taken_bits[15:13], taken_bits[1:0]};	// src/main/scala/rocket/Frontend.scala:232:37, :240:28
  wire        taken_rvcBranch = _GEN_1 == 5'h19 | _GEN_1 == 5'h1D;	// src/main/scala/rocket/Frontend.scala:240:{28,52,60}
  wire        taken_rvcJAL = _GEN_1 == 5'h5;	// src/main/scala/rocket/Frontend.scala:240:28, :241:{35,43}
  wire        taken_rvcJump = _GEN_1 == 5'h15 | taken_rvcJAL;	// src/main/scala/rocket/Frontend.scala:240:28, :241:35, :242:{26,47}
  wire [3:0]  taken_rvcImm_lo_hi = {taken_bits[11:10], taken_bits[4:3]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:45:{17,49,59}
  wire [4:0]  taken_rvcImm_lo = {taken_rvcImm_lo_hi, 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RVC.scala:45:17
  wire [6:0]  taken_rvcImm_hi_hi = {{5{taken_bits[12]}}, taken_bits[6:5]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:45:{17,22,27,35}
  wire [7:0]  taken_rvcImm_hi = {taken_rvcImm_hi_hi, taken_bits[2]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:45:{17,43}
  wire [3:0]  taken_rvcImm_lo_lo = {taken_bits[5:3], 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,76}
  wire [1:0]  taken_rvcImm_lo_hi_1 = {taken_bits[2], taken_bits[11]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,69}, :45:43
  wire [5:0]  taken_rvcImm_lo_1 = {taken_rvcImm_lo_hi_1, taken_rvcImm_lo_lo};	// src/main/scala/rocket/RVC.scala:44:17
  wire [1:0]  taken_rvcImm_hi_lo = {taken_bits[6], taken_bits[7]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,51,57}
  wire [10:0] taken_rvcImm_hi_hi_hi = {{10{taken_bits[12]}}, taken_bits[8]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,22,36}, :45:27
  wire [12:0] taken_rvcImm_hi_hi_1 = {taken_rvcImm_hi_hi_hi, taken_bits[10:9]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,42}
  wire [14:0] taken_rvcImm_hi_1 = {taken_rvcImm_hi_hi_1, taken_rvcImm_hi_lo};	// src/main/scala/rocket/RVC.scala:44:17
  wire [20:0] taken_rvcImm =
    taken_bits[14]
      ? {{8{taken_rvcImm_hi[7]}}, taken_rvcImm_hi, taken_rvcImm_lo}
      : {taken_rvcImm_hi_1, taken_rvcImm_lo_1};	// src/main/scala/rocket/Frontend.scala:232:37, :243:{23,28}, src/main/scala/rocket/RVC.scala:44:17, :45:17
  wire [5:0]  _GEN_2 = {taken_bits[15:12], taken_bits[1:0]};	// src/main/scala/rocket/Frontend.scala:232:37, :240:28, :244:24
  wire        taken_rvcJR = _GEN_2 == 6'h22 & ~(|(taken_bits[6:2]));	// src/main/scala/rocket/Frontend.scala:232:37, :244:{24,46,53,59}
  wire        taken_rvcReturn =
    taken_rvcJR & {taken_bits[11:10], taken_bits[8:7]} == 4'h1;	// src/main/scala/rocket/Frontend.scala:232:37, :244:46, :245:{29,49}
  wire        taken_rvcJALR = _GEN_2 == 6'h26 & ~(|(taken_bits[6:2]));	// src/main/scala/rocket/Frontend.scala:232:37, :244:{24,53,59}, :246:{26,49,62}
  wire        taken_rvcCall = taken_rvcJAL | taken_rvcJALR;	// src/main/scala/rocket/Frontend.scala:241:35, :246:49, :247:28
  wire        taken_rviImm_sign = taken_rviBits[31];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1102:{19,44}
  wire        taken_rviImm_sign_1 = taken_rviBits[31];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1102:{19,44}
  wire        taken_rviImm_hi_hi_hi = taken_rviImm_sign;	// src/main/scala/rocket/RocketCore.scala:1102:19, :1116:8
  wire [10:0] taken_rviImm_b30_20 = {11{taken_rviImm_sign}};	// src/main/scala/rocket/RocketCore.scala:1102:19, :1103:21
  wire [10:0] taken_rviImm_hi_hi_lo = taken_rviImm_b30_20;	// src/main/scala/rocket/RocketCore.scala:1103:21, :1116:8
  wire [7:0]  taken_rviImm_b19_12 = taken_rviBits[19:12];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1104:{21,65}
  wire [7:0]  taken_rviImm_hi_lo_hi = taken_rviImm_b19_12;	// src/main/scala/rocket/RocketCore.scala:1104:21, :1116:8
  wire        taken_rviImm_b11 = taken_rviBits[20];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1105:18, :1106:39
  wire        taken_rviImm_hi_lo_lo = taken_rviImm_b11;	// src/main/scala/rocket/RocketCore.scala:1105:18, :1116:8
  wire [5:0]  taken_rviImm_b10_5 = taken_rviBits[30:25];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1108:{20,62}
  wire [5:0]  taken_rviImm_b10_5_1 = taken_rviBits[30:25];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1108:{20,62}
  wire [3:0]  taken_rviImm_b4_1_1 = taken_rviBits[11:8];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1109:19, :1110:57
  wire [3:0]  taken_rviImm_b4_1 = taken_rviBits[24:21];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1109:19, :1111:52
  wire [9:0]  taken_rviImm_lo_hi = {taken_rviImm_b10_5, taken_rviImm_b4_1};	// src/main/scala/rocket/RocketCore.scala:1108:20, :1109:19, :1116:8
  wire [10:0] taken_rviImm_lo = {taken_rviImm_lo_hi, 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1116:8
  wire [8:0]  taken_rviImm_hi_lo = {taken_rviImm_hi_lo_hi, taken_rviImm_hi_lo_lo};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [11:0] taken_rviImm_hi_hi = {taken_rviImm_hi_hi_hi, taken_rviImm_hi_hi_lo};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [20:0] taken_rviImm_hi = {taken_rviImm_hi_hi, taken_rviImm_hi_lo};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire        taken_rviImm_hi_hi_hi_1 = taken_rviImm_sign_1;	// src/main/scala/rocket/RocketCore.scala:1102:19, :1116:8
  wire [10:0] taken_rviImm_b30_20_1 = {11{taken_rviImm_sign_1}};	// src/main/scala/rocket/RocketCore.scala:1102:19, :1103:21
  wire [10:0] taken_rviImm_hi_hi_lo_1 = taken_rviImm_b30_20_1;	// src/main/scala/rocket/RocketCore.scala:1103:21, :1116:8
  wire [7:0]  taken_rviImm_b19_12_1 = {8{taken_rviImm_sign_1}};	// src/main/scala/rocket/RocketCore.scala:1102:19, :1104:21
  wire [7:0]  taken_rviImm_hi_lo_hi_1 = taken_rviImm_b19_12_1;	// src/main/scala/rocket/RocketCore.scala:1104:21, :1116:8
  wire        taken_rviImm_hi_lo_lo_1 = taken_rviImm_b11_1;	// src/main/scala/rocket/RocketCore.scala:1105:18, :1116:8
  wire [9:0]  taken_rviImm_lo_hi_1 = {taken_rviImm_b10_5_1, taken_rviImm_b4_1_1};	// src/main/scala/rocket/RocketCore.scala:1108:20, :1109:19, :1116:8
  wire [10:0] taken_rviImm_lo_1 = {taken_rviImm_lo_hi_1, 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1116:8
  wire [8:0]  taken_rviImm_hi_lo_1 = {taken_rviImm_hi_lo_hi_1, taken_rviImm_hi_lo_lo_1};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [11:0] taken_rviImm_hi_hi_1 = {taken_rviImm_hi_hi_hi_1, taken_rviImm_hi_hi_lo_1};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [20:0] taken_rviImm_hi_1 = {taken_rviImm_hi_hi_1, taken_rviImm_hi_lo_1};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [31:0] taken_rviImm =
    taken_rviBits[3]
      ? {taken_rviImm_hi, taken_rviImm_lo}
      : {taken_rviImm_hi_1, taken_rviImm_lo_1};	// src/main/scala/rocket/Frontend.scala:234:24, :248:{23,31}, src/main/scala/rocket/RocketCore.scala:1116:8
  assign taken_taken =
    taken_prevRVI & (_taken_taken_T | taken_rviBranch & taken_predict_taken) | taken_valid
    & (taken_rvcJump | taken_rvcJALR | taken_rvcJR | taken_rvcBranch
       & taken_predict_taken);	// src/main/scala/rocket/Frontend.scala:230:31, :231:44, :235:36, :239:30, :240:52, :242:47, :244:46, :246:49, :249:54, :251:{17,40,53,71}, :252:{15,47,60}
  wire        taken_predictReturn =
    _btb_io_ras_head_valid
    & (taken_prevRVI & taken_rviReturn | taken_valid & taken_rvcReturn);	// src/main/scala/rocket/Frontend.scala:194:21, :230:31, :231:44, :238:46, :245:29, :253:{49,61,74,83}
  wire        taken_predictJump =
    taken_prevRVI & taken_rviJump | taken_valid & taken_rvcJump;	// src/main/scala/rocket/Frontend.scala:230:31, :231:44, :236:34, :242:47, :254:{33,44,53}
  wire        _taken_T_19 = taken_prevRVI & taken_rviBranch;	// src/main/scala/rocket/Frontend.scala:230:31, :235:36, :255:53
  wire        _taken_T_20 = taken_valid & taken_rvcBranch;	// src/main/scala/rocket/Frontend.scala:231:44, :240:52, :255:75
  wire        taken_predictBranch = taken_predict_taken & (_taken_T_19 | _taken_T_20);	// src/main/scala/rocket/Frontend.scala:249:54, :255:{41,53,66,75}
  wire        _taken_T_29 = s2_valid & s2_btb_resp_valid;	// src/main/scala/rocket/Frontend.scala:104:25, :114:44, :257:22
  wire        _taken_T_5 =
    _taken_T_29 & ~s2_btb_resp_bits_bridx & taken_valid & ~taken_rvc;	// src/main/scala/rocket/Frontend.scala:115:29, :229:45, :231:44, :257:{22,69,88,91}
  wire [32:0] taken_npc =
    {taken_pc[31], taken_pc}
    + (taken_prevRVI
         ? {taken_rviImm[31], taken_rviImm} - 33'h2
         : {{12{taken_rvcImm[20]}}, taken_rvcImm});	// src/main/scala/rocket/Frontend.scala:230:31, :243:23, :248:23, :283:33, :285:{39,44,61}
  wire        taken_prevRVI_1 = taken_valid & (&(taken_bits[1:0]));	// src/main/scala/rocket/Frontend.scala:229:{39,45}, :230:31, :231:44, :232:37
  wire        taken_valid_1 = _fq_io_enq_bits_mask_T_1[1] & ~taken_prevRVI_1;	// src/main/scala/rocket/Frontend.scala:185:50, :230:31, :231:{38,44,47}
  wire [15:0] taken_bits_1 = _icache_io_resp_bits_data[31:16];	// src/main/scala/rocket/Frontend.scala:66:26, :232:37
  wire        taken_rvc_1 = taken_bits_1[1:0] != 2'h3;	// src/main/scala/rocket/Frontend.scala:124:29, :229:{39,45}, :232:37
  wire [31:0] taken_rviBits_1 = {taken_bits_1, taken_bits};	// src/main/scala/rocket/Frontend.scala:232:37, :234:24
  wire        taken_rviBranch_1 = taken_rviBits_1[6:0] == 7'h63;	// src/main/scala/rocket/Frontend.scala:234:24, :235:{30,36}
  wire        taken_rviJump_1 = taken_rviBits_1[6:0] == 7'h6F;	// src/main/scala/rocket/Frontend.scala:234:24, :235:30, :236:34
  wire        taken_rviJALR_1 = taken_rviBits_1[6:0] == 7'h67;	// src/main/scala/rocket/Frontend.scala:234:24, :235:30, :237:34
  wire        taken_rviImm_b11_3 = taken_rviBits_1[7];	// src/main/scala/rocket/Frontend.scala:234:24, :238:42, src/main/scala/rocket/RocketCore.scala:1105:18
  wire        taken_rviReturn_1 =
    taken_rviJALR_1 & ~taken_rviImm_b11_3
    & {taken_rviBits_1[19:18], taken_rviBits_1[16:15]} == 4'h1;	// src/main/scala/rocket/Frontend.scala:234:24, :237:34, :238:{34,46,66}, src/main/scala/rocket/RocketCore.scala:1105:18
  wire        _taken_taken_T_9 = taken_rviJALR_1 | taken_rviJump_1;	// src/main/scala/rocket/Frontend.scala:236:34, :237:34, :239:30
  wire        taken_rviCall_1 = _taken_taken_T_9 & taken_rviImm_b11_3;	// src/main/scala/rocket/Frontend.scala:239:{30,42}, src/main/scala/rocket/RocketCore.scala:1105:18
  wire [4:0]  _GEN_3 = {taken_bits_1[15:13], taken_bits_1[1:0]};	// src/main/scala/rocket/Frontend.scala:232:37, :240:28
  wire        taken_rvcBranch_1 = _GEN_3 == 5'h19 | _GEN_3 == 5'h1D;	// src/main/scala/rocket/Frontend.scala:240:{28,52,60}
  wire        taken_rvcJAL_1 = _GEN_3 == 5'h5;	// src/main/scala/rocket/Frontend.scala:240:28, :241:{35,43}
  wire        taken_rvcJump_1 = _GEN_3 == 5'h15 | taken_rvcJAL_1;	// src/main/scala/rocket/Frontend.scala:240:28, :241:35, :242:{26,47}
  wire [3:0]  taken_rvcImm_lo_hi_2 = {taken_bits_1[11:10], taken_bits_1[4:3]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:45:{17,49,59}
  wire [4:0]  taken_rvcImm_lo_2 = {taken_rvcImm_lo_hi_2, 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RVC.scala:45:17
  wire [6:0]  taken_rvcImm_hi_hi_2 = {{5{taken_bits_1[12]}}, taken_bits_1[6:5]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:45:{17,22,27,35}
  wire [7:0]  taken_rvcImm_hi_2 = {taken_rvcImm_hi_hi_2, taken_bits_1[2]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:45:{17,43}
  wire [3:0]  taken_rvcImm_lo_lo_1 = {taken_bits_1[5:3], 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,76}
  wire [1:0]  taken_rvcImm_lo_hi_3 = {taken_bits_1[2], taken_bits_1[11]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,69}, :45:43
  wire [5:0]  taken_rvcImm_lo_3 = {taken_rvcImm_lo_hi_3, taken_rvcImm_lo_lo_1};	// src/main/scala/rocket/RVC.scala:44:17
  wire [1:0]  taken_rvcImm_hi_lo_1 = {taken_bits_1[6], taken_bits_1[7]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,51,57}
  wire [10:0] taken_rvcImm_hi_hi_hi_1 = {{10{taken_bits_1[12]}}, taken_bits_1[8]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,22,36}, :45:27
  wire [12:0] taken_rvcImm_hi_hi_3 = {taken_rvcImm_hi_hi_hi_1, taken_bits_1[10:9]};	// src/main/scala/rocket/Frontend.scala:232:37, src/main/scala/rocket/RVC.scala:44:{17,42}
  wire [14:0] taken_rvcImm_hi_3 = {taken_rvcImm_hi_hi_3, taken_rvcImm_hi_lo_1};	// src/main/scala/rocket/RVC.scala:44:17
  wire [20:0] taken_rvcImm_1 =
    taken_bits_1[14]
      ? {{8{taken_rvcImm_hi_2[7]}}, taken_rvcImm_hi_2, taken_rvcImm_lo_2}
      : {taken_rvcImm_hi_3, taken_rvcImm_lo_3};	// src/main/scala/rocket/Frontend.scala:232:37, :243:{23,28}, src/main/scala/rocket/RVC.scala:44:17, :45:17
  wire [5:0]  _GEN_4 = {taken_bits_1[15:12], taken_bits_1[1:0]};	// src/main/scala/rocket/Frontend.scala:232:37, :240:28, :244:24
  wire        taken_rvcJR_1 = _GEN_4 == 6'h22 & ~(|(taken_bits_1[6:2]));	// src/main/scala/rocket/Frontend.scala:232:37, :244:{24,46,53,59}
  wire        taken_rvcReturn_1 =
    taken_rvcJR_1 & {taken_bits_1[11:10], taken_bits_1[8:7]} == 4'h1;	// src/main/scala/rocket/Frontend.scala:232:37, :244:46, :245:{29,49}
  wire        taken_rvcJALR_1 = _GEN_4 == 6'h26 & ~(|(taken_bits_1[6:2]));	// src/main/scala/rocket/Frontend.scala:232:37, :244:{24,53,59}, :246:{26,49,62}
  wire        taken_rvcCall_1 = taken_rvcJAL_1 | taken_rvcJALR_1;	// src/main/scala/rocket/Frontend.scala:241:35, :246:49, :247:28
  wire        taken_rviImm_sign_2 = taken_rviBits_1[31];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1102:{19,44}
  wire        taken_rviImm_sign_3 = taken_rviBits_1[31];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1102:{19,44}
  wire        taken_rviImm_hi_hi_hi_2 = taken_rviImm_sign_2;	// src/main/scala/rocket/RocketCore.scala:1102:19, :1116:8
  wire [10:0] taken_rviImm_b30_20_2 = {11{taken_rviImm_sign_2}};	// src/main/scala/rocket/RocketCore.scala:1102:19, :1103:21
  wire [10:0] taken_rviImm_hi_hi_lo_2 = taken_rviImm_b30_20_2;	// src/main/scala/rocket/RocketCore.scala:1103:21, :1116:8
  wire [7:0]  taken_rviImm_b19_12_2 = taken_rviBits_1[19:12];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1104:{21,65}
  wire [7:0]  taken_rviImm_hi_lo_hi_2 = taken_rviImm_b19_12_2;	// src/main/scala/rocket/RocketCore.scala:1104:21, :1116:8
  wire        taken_rviImm_b11_2 = taken_rviBits_1[20];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1105:18, :1106:39
  wire        taken_rviImm_hi_lo_lo_2 = taken_rviImm_b11_2;	// src/main/scala/rocket/RocketCore.scala:1105:18, :1116:8
  wire [5:0]  taken_rviImm_b10_5_2 = taken_rviBits_1[30:25];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1108:{20,62}
  wire [5:0]  taken_rviImm_b10_5_3 = taken_rviBits_1[30:25];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1108:{20,62}
  wire [3:0]  taken_rviImm_b4_1_3 = taken_rviBits_1[11:8];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1109:19, :1110:57
  wire [3:0]  taken_rviImm_b4_1_2 = taken_rviBits_1[24:21];	// src/main/scala/rocket/Frontend.scala:234:24, src/main/scala/rocket/RocketCore.scala:1109:19, :1111:52
  wire [9:0]  taken_rviImm_lo_hi_2 = {taken_rviImm_b10_5_2, taken_rviImm_b4_1_2};	// src/main/scala/rocket/RocketCore.scala:1108:20, :1109:19, :1116:8
  wire [10:0] taken_rviImm_lo_2 = {taken_rviImm_lo_hi_2, 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1116:8
  wire [8:0]  taken_rviImm_hi_lo_2 = {taken_rviImm_hi_lo_hi_2, taken_rviImm_hi_lo_lo_2};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [11:0] taken_rviImm_hi_hi_2 = {taken_rviImm_hi_hi_hi_2, taken_rviImm_hi_hi_lo_2};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [20:0] taken_rviImm_hi_2 = {taken_rviImm_hi_hi_2, taken_rviImm_hi_lo_2};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire        taken_rviImm_hi_hi_hi_3 = taken_rviImm_sign_3;	// src/main/scala/rocket/RocketCore.scala:1102:19, :1116:8
  wire [10:0] taken_rviImm_b30_20_3 = {11{taken_rviImm_sign_3}};	// src/main/scala/rocket/RocketCore.scala:1102:19, :1103:21
  wire [10:0] taken_rviImm_hi_hi_lo_3 = taken_rviImm_b30_20_3;	// src/main/scala/rocket/RocketCore.scala:1103:21, :1116:8
  wire [7:0]  taken_rviImm_b19_12_3 = {8{taken_rviImm_sign_3}};	// src/main/scala/rocket/RocketCore.scala:1102:19, :1104:21
  wire [7:0]  taken_rviImm_hi_lo_hi_3 = taken_rviImm_b19_12_3;	// src/main/scala/rocket/RocketCore.scala:1104:21, :1116:8
  wire        taken_rviImm_hi_lo_lo_3 = taken_rviImm_b11_3;	// src/main/scala/rocket/RocketCore.scala:1105:18, :1116:8
  wire [9:0]  taken_rviImm_lo_hi_3 = {taken_rviImm_b10_5_3, taken_rviImm_b4_1_3};	// src/main/scala/rocket/RocketCore.scala:1108:20, :1109:19, :1116:8
  wire [10:0] taken_rviImm_lo_3 = {taken_rviImm_lo_hi_3, 1'h0};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/RocketCore.scala:1116:8
  wire [8:0]  taken_rviImm_hi_lo_3 = {taken_rviImm_hi_lo_hi_3, taken_rviImm_hi_lo_lo_3};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [11:0] taken_rviImm_hi_hi_3 = {taken_rviImm_hi_hi_hi_3, taken_rviImm_hi_hi_lo_3};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [20:0] taken_rviImm_hi_3 = {taken_rviImm_hi_hi_3, taken_rviImm_hi_lo_3};	// src/main/scala/rocket/RocketCore.scala:1116:8
  wire [31:0] taken_rviImm_1 =
    taken_rviBits_1[3]
      ? {taken_rviImm_hi_2, taken_rviImm_lo_2}
      : {taken_rviImm_hi_3, taken_rviImm_lo_3};	// src/main/scala/rocket/Frontend.scala:234:24, :248:{23,31}, src/main/scala/rocket/RocketCore.scala:1116:8
  wire        taken_taken_1 =
    taken_prevRVI_1 & (_taken_taken_T_9 | taken_rviBranch_1 & taken_predict_taken_1)
    | taken_valid_1
    & (taken_rvcJump_1 | taken_rvcJALR_1 | taken_rvcJR_1 | taken_rvcBranch_1
       & taken_predict_taken_1);	// src/main/scala/rocket/Frontend.scala:230:31, :231:44, :235:36, :239:30, :240:52, :242:47, :244:46, :246:49, :249:54, :251:{17,40,53,71}, :252:{15,47,60}
  wire        taken_predictReturn_1 =
    _btb_io_ras_head_valid
    & (taken_prevRVI_1 & taken_rviReturn_1 | taken_valid_1 & taken_rvcReturn_1);	// src/main/scala/rocket/Frontend.scala:194:21, :230:31, :231:44, :238:46, :245:29, :253:{49,61,74,83}
  wire        taken_predictJump_1 =
    taken_prevRVI_1 & taken_rviJump_1 | taken_valid_1 & taken_rvcJump_1;	// src/main/scala/rocket/Frontend.scala:230:31, :231:44, :236:34, :242:47, :254:{33,44,53}
  wire        _taken_T_48 = taken_prevRVI_1 & taken_rviBranch_1;	// src/main/scala/rocket/Frontend.scala:230:31, :235:36, :255:53
  wire        _taken_T_49 = taken_valid_1 & taken_rvcBranch_1;	// src/main/scala/rocket/Frontend.scala:231:44, :240:52, :255:75
  wire        taken_predictBranch_1 = taken_predict_taken_1 & (_taken_T_48 | _taken_T_49);	// src/main/scala/rocket/Frontend.scala:249:54, :255:{41,53,66,75}
  wire        _taken_T_34 =
    _taken_T_29 & s2_btb_resp_bits_bridx & taken_valid_1 & ~taken_rvc_1;	// src/main/scala/rocket/Frontend.scala:115:29, :229:45, :231:44, :257:{22,88,91}
  assign after_idx = taken_taken ? 2'h1 : 2'h2;	// src/main/scala/rocket/Frontend.scala:163:24, :220:25, :251:71, :266:25, :268:19
  assign _GEN =
    taken_taken
      ? ((taken_prevRVI ? taken_rviReturn : taken_rvcReturn)
           ? 2'h3
           : (taken_prevRVI ? taken_rviCall : taken_rvcCall)
               ? 2'h2
               : {1'h0, ~(taken_prevRVI ? taken_rviBranch : taken_rvcBranch)})
      : (taken_prevRVI_1 ? taken_rviReturn_1 : taken_rvcReturn_1)
          ? 2'h3
          : (taken_prevRVI_1 ? taken_rviCall_1 : taken_rvcCall_1)
              ? 2'h2
              : {1'h0, ~(taken_prevRVI_1 ? taken_rviBranch_1 : taken_rvcBranch_1)};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:89:25, :92:9, :124:29, :163:24, :230:31, :235:36, :238:46, :239:42, :240:52, :245:29, :247:28, :251:71, :266:25, :270:{40,46,50}, :271:{46,50}, :272:{46,50}
  wire        useRAS =
    ~taken_taken & ~s2_btb_taken & s2_valid & taken_predictReturn_1 | ~s2_btb_taken
    & s2_valid & taken_predictReturn;	// src/main/scala/rocket/Frontend.scala:104:25, :116:40, :221:29, :251:71, :253:49, :266:{13,25}, :275:{15,30}, :279:44, :280:20
  wire [31:0] taken_pc_1 = {s2_base_pc[31:2], s2_base_pc[1:0] | 2'h2};	// src/main/scala/rocket/Frontend.scala:163:24, :218:22, :283:33, :319:50
  wire [31:0] taken_npc_1 =
    (taken_prevRVI_1 ? taken_pc_1 - 32'h2 : taken_pc_1)
    + (taken_prevRVI_1 ? taken_rviImm_1 : {{11{taken_rvcImm_1[20]}}, taken_rvcImm_1});	// src/main/scala/rocket/Frontend.scala:230:31, :243:23, :248:23, :283:33, :286:{23,36,66,71}
  assign updateBTB =
    ~taken_taken & ~s2_btb_resp_valid
    & (taken_predictBranch_1 & s2_btb_resp_bits_bht_value | taken_predictJump_1
       | taken_predictReturn_1) | ~s2_btb_resp_valid
    & (taken_predictBranch & s2_btb_resp_bits_bht_value | taken_predictJump
       | taken_predictReturn);	// src/main/scala/rocket/Frontend.scala:114:44, :115:29, :222:32, :251:71, :253:49, :254:44, :255:41, :266:{13,25}, :294:{15,34,52,106,125}, :295:21
  wire        taken = taken_taken | taken_taken_1;	// src/main/scala/rocket/Frontend.scala:251:71, :307:19
  assign predicted_npc =
    useRAS
      ? {1'h0, _btb_io_ras_head_bits}
      : ~taken_taken & ~s2_btb_taken & s2_valid
        & (taken_predictBranch_1 | taken_predictJump_1)
          ? {1'h0, taken_npc_1}
          : ~s2_btb_taken & s2_valid & (taken_predictBranch | taken_predictJump)
              ? taken_npc
              : {1'h0, predicted_taken ? _btb_io_resp_bits_target : ntpc};	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:104:25, :116:40, :125:25, :126:34, :127:36, :194:21, :209:56, :210:21, :221:29, :251:71, :254:44, :255:41, :266:{13,25}, :275:{15,30}, :282:{44,61}, :285:39, :286:66, :287:27, :326:19, :327:21
  wire        _GEN_5 = ~s2_btb_taken & taken;	// src/main/scala/rocket/Frontend.scala:116:40, :187:22, :307:19, :332:{11,26}, :333:20, :334:34
  assign s2_redirect = ~s2_btb_taken & taken & _T_37 | io_cpu_req_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:116:40, :141:32, :307:19, :332:{11,26}, :333:20, :337:{31,45}
  reg         gpa_valid;	// src/main/scala/rocket/Frontend.scala:349:22
  reg  [31:0] gpa;	// src/main/scala/rocket/Frontend.scala:350:16
  always @(posedge clock) begin
    automatic logic _taken_T_61;	// src/main/scala/rocket/Frontend.scala:302:37
    automatic logic _T_38;	// src/main/scala/rocket/Frontend.scala:351:24
    _taken_T_61 = taken_valid_1 & ~taken_taken & ~taken_rvc_1;	// src/main/scala/rocket/Frontend.scala:229:45, :231:44, :251:71, :257:91, :266:13, :302:37
    _T_38 = _T_37 & s2_tlb_resp_gf_inst;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:117:24, :351:24
    s1_valid <= s0_valid;	// src/main/scala/rocket/Frontend.scala:103:21, :109:35
    s1_pc <= _GEN_0;	// src/main/scala/rocket/Frontend.scala:111:18, :182:14
    if (io_cpu_req_valid)	// src/main/scala/rocket/Frontend.scala:81:14
      s1_speculative <= io_cpu_req_bits_speculative;	// src/main/scala/rocket/Frontend.scala:112:27
    else if (s2_replay)	// src/main/scala/rocket/Frontend.scala:129:23
      s1_speculative <= s2_speculative;	// src/main/scala/rocket/Frontend.scala:112:27, :119:31
    else	// src/main/scala/rocket/Frontend.scala:129:23
      s1_speculative <= s0_speculative;	// src/main/scala/rocket/Frontend.scala:112:27, :137:72
    if (s2_replay) begin	// src/main/scala/rocket/Frontend.scala:129:23
    end
    else begin	// src/main/scala/rocket/Frontend.scala:129:23
      s2_btb_resp_valid <= _btb_io_resp_valid;	// src/main/scala/rocket/Frontend.scala:114:44, :194:21
      s2_btb_resp_bits_cfiType <= _btb_io_resp_bits_cfiType;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_btb_resp_bits_taken <= _btb_io_resp_bits_taken;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_btb_resp_bits_mask <= _btb_io_resp_bits_mask;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_btb_resp_bits_bridx <= _btb_io_resp_bits_bridx;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_btb_resp_bits_target <= _btb_io_resp_bits_target;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_btb_resp_bits_entry <= _btb_io_resp_bits_entry;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_btb_resp_bits_bht_history <= _btb_io_resp_bits_bht_history;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_btb_resp_bits_bht_value <= _btb_io_resp_bits_bht_value;	// src/main/scala/rocket/Frontend.scala:115:29, :194:21
      s2_tlb_resp_paddr <= _tlb_io_resp_paddr;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
      s2_tlb_resp_gpa <= _tlb_io_resp_gpa;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
      s2_tlb_resp_pf_ld <= _tlb_io_resp_pf_ld;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
      s2_tlb_resp_pf_inst <= _tlb_io_resp_pf_inst;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
      s2_tlb_resp_ae_ld <= _tlb_io_resp_ae_ld;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
      s2_tlb_resp_ae_inst <= _tlb_io_resp_ae_inst;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
      s2_tlb_resp_ma_ld <= _tlb_io_resp_ma_ld;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
      s2_tlb_resp_cacheable <= _tlb_io_resp_cacheable;	// src/main/scala/rocket/Frontend.scala:101:19, :117:24
    end
    s2_tlb_resp_miss <= s2_replay & s2_tlb_resp_miss;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_gpa_is_pte <= s2_replay & s2_tlb_resp_gpa_is_pte;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_pf_st <= s2_replay & s2_tlb_resp_pf_st;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_gf_ld <= s2_replay & s2_tlb_resp_gf_ld;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_gf_st <= s2_replay & s2_tlb_resp_gf_st;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_gf_inst <= s2_replay & s2_tlb_resp_gf_inst;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_ae_st <= s2_replay & s2_tlb_resp_ae_st;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_ma_st <= s2_replay & s2_tlb_resp_ma_st;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_ma_inst <= s2_replay & s2_tlb_resp_ma_inst;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_must_alloc <= s2_replay & s2_tlb_resp_must_alloc;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    s2_tlb_resp_prefetchable <= s2_replay & s2_tlb_resp_prefetchable;	// src/main/scala/rocket/Frontend.scala:117:24, :129:23, :143:21, :147:17
    if (_T_37 & _taken_T_61)	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:121:28, :300:31, :302:{37,46}, :304:29
      s2_partial_insn <= {taken_bits_1[15:2], 2'h3};	// src/main/scala/rocket/Frontend.scala:121:28, :124:29, :232:37, :304:37
    fq_io_enq_valid_REG <= s1_valid;	// src/main/scala/rocket/Frontend.scala:103:21, :180:29
    if (_T_38 & ~gpa_valid)	// src/main/scala/rocket/Frontend.scala:349:22, :350:16, :351:{24,48}, :352:{11,23}, :353:11
      gpa <= s2_tlb_resp_gpa;	// src/main/scala/rocket/Frontend.scala:117:24, :350:16
    if (reset) begin
      s2_valid <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:104:25
      s2_pc <= 32'h10040;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:113:22
      s2_speculative <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:119:31
      s2_partial_insn_valid <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:120:38
      wrong_path <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:122:27
      s2_replay_REG <= 1'h1;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:130:56
      recent_progress_counter <= 2'h3;	// src/main/scala/rocket/Frontend.scala:124:29, :151:40
    end
    else begin
      automatic logic _GEN_6;	// src/main/scala/rocket/Frontend.scala:257:97, :275:30, :276:94
      _GEN_6 =
        s2_btb_taken
          ? _taken_T_5 | wrong_path
          : _T_37 & taken_taken & ~taken_predictBranch & ~taken_predictJump
            & ~taken_predictReturn | _taken_T_5 | wrong_path;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:116:40, :122:27, :251:71, :253:49, :254:44, :255:41, :257:{88,97}, :262:20, :275:30, :276:{44,62,75,78,94}, :277:24
      s2_valid <= ~s2_replay & ~s2_redirect;	// src/main/scala/rocket/Frontend.scala:104:25, :129:23, :141:32, :142:12, :143:{9,21}, :144:{14,17}
      if (s2_replay) begin	// src/main/scala/rocket/Frontend.scala:129:23
      end
      else begin	// src/main/scala/rocket/Frontend.scala:129:23
        s2_pc <= s1_pc;	// src/main/scala/rocket/Frontend.scala:111:18, :113:22
        s2_speculative <= s1_speculative;	// src/main/scala/rocket/Frontend.scala:112:27, :119:31
      end
      s2_partial_insn_valid <=
        ~(s2_redirect | _T_37 & (s2_btb_taken | taken))
        & (_T_37 ? _taken_T_61 : s2_partial_insn_valid);	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:116:40, :120:38, :141:32, :300:31, :302:{37,46}, :307:19, :329:{26,43,54}, :330:29, :342:{24,48}
      wrong_path <=
        ~io_cpu_req_valid
        & (taken_taken | s2_btb_taken
             ? _taken_T_34 | _GEN_6
             : _T_37 & taken_taken_1 & ~taken_predictBranch_1 & ~taken_predictJump_1
               & ~taken_predictReturn_1 | _taken_T_34 | _GEN_6);	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:116:40, :122:27, :251:71, :253:49, :254:44, :255:41, :257:{88,97}, :262:20, :266:25, :275:30, :276:{44,62,75,78,94}, :277:24, :343:{29,42}
      s2_replay_REG <= s2_replay & ~s0_valid;	// src/main/scala/rocket/Frontend.scala:109:35, :129:23, :130:{56,67,70}
      if (io_cpu_progress)	// src/main/scala/rocket/Frontend.scala:81:14
        recent_progress_counter <= 2'h3;	// src/main/scala/rocket/Frontend.scala:124:29, :151:40
      else if (io_ptw_req_ready & _tlb_io_ptw_req_valid & recent_progress)	// src/main/scala/rocket/Frontend.scala:101:19, :152:49, :153:24
        recent_progress_counter <= recent_progress_counter - 2'h1;	// src/main/scala/rocket/Frontend.scala:151:40, :153:97
    end
    if (io_cpu_req_valid)
      gpa_valid <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:349:22
    else
      gpa_valid <= _T_38 | gpa_valid;	// src/main/scala/rocket/Frontend.scala:349:22, :351:{24,48}, :355:15
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// src/main/scala/rocket/Frontend.scala:92:9
      if (~reset
          & ~(~(io_cpu_req_valid | io_cpu_sfence_valid | io_cpu_flush_icache
                | io_cpu_bht_update_valid | io_cpu_btb_update_valid)
              | io_cpu_might_request)) begin	// src/main/scala/rocket/Frontend.scala:92:{9,10,102,130}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/rocket/Frontend.scala:92:9
          $error("Assertion failed\n    at Frontend.scala:92 assert(!(io.cpu.req.valid || io.cpu.sfence.valid || io.cpu.flush_icache || io.cpu.bht_update.valid || io.cpu.btb_update.valid) || io.cpu.might_request)\n");	// src/main/scala/rocket/Frontend.scala:92:9
        if (`STOP_COND_)	// src/main/scala/rocket/Frontend.scala:92:9
          $fatal;	// src/main/scala/rocket/Frontend.scala:92:9
      end
      if (~reset & s2_speculative & io_ptw_customCSRs_csrs_0_value[3]
          & ~_icache_io_s2_kill_T_2) begin	// src/main/scala/rocket/Frontend.scala:119:31, :176:71, :190:{9,113}, src/main/scala/tile/CustomCSRs.scala:46:69
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/rocket/Frontend.scala:190:9
          $error("Assertion failed\n    at Frontend.scala:190 assert(!(s2_speculative && io.ptw.customCSRs.asInstanceOf[RocketCustomCSRs].disableSpeculativeICacheRefill && !icache.io.s2_kill))\n");	// src/main/scala/rocket/Frontend.scala:190:9
        if (`STOP_COND_)	// src/main/scala/rocket/Frontend.scala:190:9
          $fatal;	// src/main/scala/rocket/Frontend.scala:190:9
      end
      if (~reset & ~(~s2_partial_insn_valid | _fq_io_enq_bits_mask_T_1[0])) begin	// src/main/scala/rocket/Frontend.scala:120:38, :185:50, :231:38, :341:{11,12,35}
        if (`ASSERT_VERBOSE_COND_)	// src/main/scala/rocket/Frontend.scala:341:11
          $error("Assertion failed\n    at Frontend.scala:341 assert(!s2_partial_insn_valid || fq.io.enq.bits.mask(0))\n");	// src/main/scala/rocket/Frontend.scala:341:11
        if (`STOP_COND_)	// src/main/scala/rocket/Frontend.scala:341:11
          $fatal;	// src/main/scala/rocket/Frontend.scala:341:11
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:8];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h9; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        s1_valid = _RANDOM[4'h0][1];	// src/main/scala/rocket/Frontend.scala:103:21
        s2_valid = _RANDOM[4'h0][2];	// src/main/scala/rocket/Frontend.scala:103:21, :104:25
        s1_pc = {_RANDOM[4'h0][31:3], _RANDOM[4'h1][2:0]};	// src/main/scala/rocket/Frontend.scala:103:21, :111:18
        s1_speculative = _RANDOM[4'h1][3];	// src/main/scala/rocket/Frontend.scala:111:18, :112:27
        s2_pc = {_RANDOM[4'h1][31:4], _RANDOM[4'h2][3:0]};	// src/main/scala/rocket/Frontend.scala:111:18, :113:22
        s2_btb_resp_valid = _RANDOM[4'h2][4];	// src/main/scala/rocket/Frontend.scala:113:22, :114:44
        s2_btb_resp_bits_cfiType = _RANDOM[4'h2][6:5];	// src/main/scala/rocket/Frontend.scala:113:22, :115:29
        s2_btb_resp_bits_taken = _RANDOM[4'h2][7];	// src/main/scala/rocket/Frontend.scala:113:22, :115:29
        s2_btb_resp_bits_mask = _RANDOM[4'h2][9:8];	// src/main/scala/rocket/Frontend.scala:113:22, :115:29
        s2_btb_resp_bits_bridx = _RANDOM[4'h2][10];	// src/main/scala/rocket/Frontend.scala:113:22, :115:29
        s2_btb_resp_bits_target = {_RANDOM[4'h2][31:11], _RANDOM[4'h3][10:0]};	// src/main/scala/rocket/Frontend.scala:113:22, :115:29
        s2_btb_resp_bits_entry = _RANDOM[4'h3][15:11];	// src/main/scala/rocket/Frontend.scala:115:29
        s2_btb_resp_bits_bht_history = _RANDOM[4'h3][23:16];	// src/main/scala/rocket/Frontend.scala:115:29
        s2_btb_resp_bits_bht_value = _RANDOM[4'h3][24];	// src/main/scala/rocket/Frontend.scala:115:29
        s2_tlb_resp_miss = _RANDOM[4'h3][25];	// src/main/scala/rocket/Frontend.scala:115:29, :117:24
        s2_tlb_resp_paddr = {_RANDOM[4'h3][31:26], _RANDOM[4'h4][25:0]};	// src/main/scala/rocket/Frontend.scala:115:29, :117:24
        s2_tlb_resp_gpa = {_RANDOM[4'h4][31:26], _RANDOM[4'h5][25:0]};	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_gpa_is_pte = _RANDOM[4'h5][26];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_pf_ld = _RANDOM[4'h5][27];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_pf_st = _RANDOM[4'h5][28];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_pf_inst = _RANDOM[4'h5][29];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_gf_ld = _RANDOM[4'h5][30];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_gf_st = _RANDOM[4'h5][31];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_gf_inst = _RANDOM[4'h6][0];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_ae_ld = _RANDOM[4'h6][1];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_ae_st = _RANDOM[4'h6][2];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_ae_inst = _RANDOM[4'h6][3];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_ma_ld = _RANDOM[4'h6][4];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_ma_st = _RANDOM[4'h6][5];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_ma_inst = _RANDOM[4'h6][6];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_cacheable = _RANDOM[4'h6][7];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_must_alloc = _RANDOM[4'h6][8];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_tlb_resp_prefetchable = _RANDOM[4'h6][9];	// src/main/scala/rocket/Frontend.scala:117:24
        s2_speculative = _RANDOM[4'h6][10];	// src/main/scala/rocket/Frontend.scala:117:24, :119:31
        s2_partial_insn_valid = _RANDOM[4'h6][11];	// src/main/scala/rocket/Frontend.scala:117:24, :120:38
        s2_partial_insn = _RANDOM[4'h6][27:12];	// src/main/scala/rocket/Frontend.scala:117:24, :121:28
        wrong_path = _RANDOM[4'h6][28];	// src/main/scala/rocket/Frontend.scala:117:24, :122:27
        s2_replay_REG = _RANDOM[4'h6][29];	// src/main/scala/rocket/Frontend.scala:117:24, :130:56
        recent_progress_counter = _RANDOM[4'h6][31:30];	// src/main/scala/rocket/Frontend.scala:117:24, :151:40
        fq_io_enq_valid_REG = _RANDOM[4'h7][0];	// src/main/scala/rocket/Frontend.scala:180:29
        gpa_valid = _RANDOM[4'h7][1];	// src/main/scala/rocket/Frontend.scala:180:29, :349:22
        gpa = {_RANDOM[4'h7][31:2], _RANDOM[4'h8][1:0]};	// src/main/scala/rocket/Frontend.scala:180:29, :350:16
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  ICache icache (	// src/main/scala/rocket/Frontend.scala:66:26
    .clock                                            (clock),
    .reset                                            (reset),
    .auto_master_out_a_ready                          (auto_icache_master_out_a_ready),
    .auto_master_out_d_valid                          (auto_icache_master_out_d_valid),
    .auto_master_out_d_bits_opcode
      (auto_icache_master_out_d_bits_opcode),
    .auto_master_out_d_bits_param
      (auto_icache_master_out_d_bits_param),
    .auto_master_out_d_bits_size
      (auto_icache_master_out_d_bits_size),
    .auto_master_out_d_bits_sink
      (auto_icache_master_out_d_bits_sink),
    .auto_master_out_d_bits_denied
      (auto_icache_master_out_d_bits_denied),
    .auto_master_out_d_bits_data
      (auto_icache_master_out_d_bits_data),
    .auto_master_out_d_bits_corrupt
      (auto_icache_master_out_d_bits_corrupt),
    .io_req_valid                                     (s0_valid),	// src/main/scala/rocket/Frontend.scala:109:35
    .io_req_bits_addr                                 (_GEN_0),	// src/main/scala/rocket/Frontend.scala:182:14
    .io_s1_paddr                                      (_tlb_io_resp_paddr),	// src/main/scala/rocket/Frontend.scala:101:19
    .io_s2_vaddr                                      (s2_pc),	// src/main/scala/rocket/Frontend.scala:113:22
    .io_s1_kill                                       (s2_redirect | s2_replay),	// src/main/scala/rocket/Frontend.scala:129:23, :141:32, :174:56
    .io_s2_kill                                       (_icache_io_s2_kill_T_2),	// src/main/scala/rocket/Frontend.scala:176:71
    .io_s2_cacheable                                  (s2_tlb_resp_cacheable),	// src/main/scala/rocket/Frontend.scala:117:24
    .io_invalidate                                    (io_cpu_flush_icache),
    .auto_master_out_a_valid                          (auto_icache_master_out_a_valid),
    .auto_master_out_a_bits_address
      (auto_icache_master_out_a_bits_address),
    .auto_master_out_a_bits_user_amba_prot_readalloc
      (auto_icache_master_out_a_bits_user_amba_prot_readalloc),
    .auto_master_out_a_bits_user_amba_prot_writealloc
      (auto_icache_master_out_a_bits_user_amba_prot_writealloc),
    .auto_master_out_d_ready                          (auto_icache_master_out_d_ready),
    .io_resp_valid                                    (_icache_io_resp_valid),
    .io_resp_bits_data                                (_icache_io_resp_bits_data),
    .io_resp_bits_replay                              (_icache_io_resp_bits_replay),
    .io_resp_bits_ae                                  (_icache_io_resp_bits_ae)
  );
  ShiftQueue fq (	// src/main/scala/rocket/Frontend.scala:87:64
    .clock                       (clock),
    .reset                       (reset | io_cpu_req_valid),	// src/main/scala/rocket/Frontend.scala:87:35
    .io_enq_valid                (_fq_io_enq_valid_T_6),	// src/main/scala/rocket/Frontend.scala:180:52
    .io_enq_bits_btb_cfiType     (s2_btb_resp_bits_cfiType),	// src/main/scala/rocket/Frontend.scala:115:29
    .io_enq_bits_btb_taken       (_GEN_5 | s2_btb_taken),	// src/main/scala/rocket/Frontend.scala:116:40, :187:22, :188:28, :332:26, :333:20, :334:34, :335:34
    .io_enq_bits_btb_mask        (s2_btb_resp_bits_mask),	// src/main/scala/rocket/Frontend.scala:115:29
    .io_enq_bits_btb_bridx       (_GEN_5 ? taken_idx : s2_btb_resp_bits_bridx),	// src/main/scala/rocket/Frontend.scala:115:29, :187:22, :219:25, :332:26, :333:20, :334:34
    .io_enq_bits_btb_target      (s2_btb_resp_bits_target),	// src/main/scala/rocket/Frontend.scala:115:29
    .io_enq_bits_btb_entry       (_GEN_5 ? 5'h1C : s2_btb_resp_bits_entry),	// src/main/scala/rocket/Frontend.scala:115:29, :187:22, :316:47, :332:26, :333:20, :334:34, :336:34
    .io_enq_bits_btb_bht_history (s2_btb_resp_bits_bht_history),	// src/main/scala/rocket/Frontend.scala:115:29
    .io_enq_bits_btb_bht_value   (s2_btb_resp_bits_bht_value),	// src/main/scala/rocket/Frontend.scala:115:29
    .io_enq_bits_pc              (s2_pc),	// src/main/scala/rocket/Frontend.scala:113:22
    .io_enq_bits_data            (_icache_io_resp_bits_data),	// src/main/scala/rocket/Frontend.scala:66:26
    .io_enq_bits_mask            (_fq_io_enq_bits_mask_T_1[1:0]),	// src/main/scala/rocket/Frontend.scala:185:{23,50}
    .io_enq_bits_xcpt_pf_inst    (s2_tlb_resp_pf_inst),	// src/main/scala/rocket/Frontend.scala:117:24
    .io_enq_bits_xcpt_gf_inst    (s2_tlb_resp_gf_inst),	// src/main/scala/rocket/Frontend.scala:117:24
    .io_enq_bits_xcpt_ae_inst
      (_icache_io_resp_valid & _icache_io_resp_bits_ae | s2_tlb_resp_ae_inst),	// src/main/scala/rocket/Frontend.scala:66:26, :117:24, :189:23, :191:{30,57,87}
    .io_enq_bits_replay
      (_taken_T_34 | _taken_T_5 | _icache_io_resp_bits_replay | _icache_io_s2_kill_T_2
       & ~_icache_io_resp_valid & ~s2_xcpt | _fq_io_enq_bits_replay_T_5),	// src/main/scala/rocket/Frontend.scala:66:26, :118:60, :176:71, :180:112, :186:{25,80,102,105}, :257:{88,97}, :261:31
    .io_deq_ready                (io_cpu_resp_ready),
    .io_enq_ready                (_fq_io_enq_ready),
    .io_deq_valid                (io_cpu_resp_valid),
    .io_deq_bits_btb_cfiType     (io_cpu_resp_bits_btb_cfiType),
    .io_deq_bits_btb_taken       (io_cpu_resp_bits_btb_taken),
    .io_deq_bits_btb_mask        (io_cpu_resp_bits_btb_mask),
    .io_deq_bits_btb_bridx       (io_cpu_resp_bits_btb_bridx),
    .io_deq_bits_btb_target      (io_cpu_resp_bits_btb_target),
    .io_deq_bits_btb_entry       (io_cpu_resp_bits_btb_entry),
    .io_deq_bits_btb_bht_history (io_cpu_resp_bits_btb_bht_history),
    .io_deq_bits_btb_bht_value   (io_cpu_resp_bits_btb_bht_value),
    .io_deq_bits_pc              (io_cpu_resp_bits_pc),
    .io_deq_bits_data            (io_cpu_resp_bits_data),
    .io_deq_bits_mask            (io_cpu_resp_bits_mask),
    .io_deq_bits_xcpt_pf_inst    (io_cpu_resp_bits_xcpt_pf_inst),
    .io_deq_bits_xcpt_gf_inst    (io_cpu_resp_bits_xcpt_gf_inst),
    .io_deq_bits_xcpt_ae_inst    (io_cpu_resp_bits_xcpt_ae_inst),
    .io_deq_bits_replay          (io_cpu_resp_bits_replay),
    .io_mask                     (_fq_io_mask)
  );
  TLB_1 tlb (	// src/main/scala/rocket/Frontend.scala:101:19
    .io_req_bits_vaddr             (s1_pc),	// src/main/scala/rocket/Frontend.scala:111:18
    .io_req_bits_prv               (io_ptw_status_prv),
    .io_sfence_valid               (io_cpu_sfence_valid),
    .io_ptw_resp_bits_ae_ptw       (io_ptw_resp_bits_ae_ptw),
    .io_ptw_resp_bits_ae_final     (io_ptw_resp_bits_ae_final),
    .io_ptw_resp_bits_pf           (io_ptw_resp_bits_pf),
    .io_ptw_resp_bits_gf           (io_ptw_resp_bits_gf),
    .io_ptw_resp_bits_hr           (io_ptw_resp_bits_hr),
    .io_ptw_resp_bits_hw           (io_ptw_resp_bits_hw),
    .io_ptw_resp_bits_hx           (io_ptw_resp_bits_hx),
    .io_ptw_resp_bits_pte_ppn      (io_ptw_resp_bits_pte_ppn),
    .io_ptw_resp_bits_pte_d        (io_ptw_resp_bits_pte_d),
    .io_ptw_resp_bits_pte_a        (io_ptw_resp_bits_pte_a),
    .io_ptw_resp_bits_pte_g        (io_ptw_resp_bits_pte_g),
    .io_ptw_resp_bits_pte_u        (io_ptw_resp_bits_pte_u),
    .io_ptw_resp_bits_pte_x        (io_ptw_resp_bits_pte_x),
    .io_ptw_resp_bits_pte_w        (io_ptw_resp_bits_pte_w),
    .io_ptw_resp_bits_pte_r        (io_ptw_resp_bits_pte_r),
    .io_ptw_resp_bits_pte_v        (io_ptw_resp_bits_pte_v),
    .io_ptw_resp_bits_gpa_is_pte   (io_ptw_resp_bits_gpa_is_pte),
    .io_ptw_ptbr_mode              (io_ptw_ptbr_mode),
    .io_ptw_ptbr_asid              (io_ptw_ptbr_asid),
    .io_ptw_ptbr_ppn               (io_ptw_ptbr_ppn),
    .io_ptw_status_debug           (io_ptw_status_debug),
    .io_ptw_status_mxr             (io_ptw_status_mxr),
    .io_ptw_status_sum             (io_ptw_status_sum),
    .io_ptw_pmp_0_cfg_l            (io_ptw_pmp_0_cfg_l),
    .io_ptw_pmp_0_cfg_res          (io_ptw_pmp_0_cfg_res),
    .io_ptw_pmp_0_cfg_a            (io_ptw_pmp_0_cfg_a),
    .io_ptw_pmp_0_cfg_x            (io_ptw_pmp_0_cfg_x),
    .io_ptw_pmp_0_cfg_w            (io_ptw_pmp_0_cfg_w),
    .io_ptw_pmp_0_cfg_r            (io_ptw_pmp_0_cfg_r),
    .io_ptw_pmp_0_addr             (io_ptw_pmp_0_addr),
    .io_ptw_pmp_0_mask             (io_ptw_pmp_0_mask),
    .io_ptw_pmp_1_cfg_l            (io_ptw_pmp_1_cfg_l),
    .io_ptw_pmp_1_cfg_res          (io_ptw_pmp_1_cfg_res),
    .io_ptw_pmp_1_cfg_a            (io_ptw_pmp_1_cfg_a),
    .io_ptw_pmp_1_cfg_x            (io_ptw_pmp_1_cfg_x),
    .io_ptw_pmp_1_cfg_w            (io_ptw_pmp_1_cfg_w),
    .io_ptw_pmp_1_cfg_r            (io_ptw_pmp_1_cfg_r),
    .io_ptw_pmp_1_addr             (io_ptw_pmp_1_addr),
    .io_ptw_pmp_1_mask             (io_ptw_pmp_1_mask),
    .io_ptw_pmp_2_cfg_l            (io_ptw_pmp_2_cfg_l),
    .io_ptw_pmp_2_cfg_res          (io_ptw_pmp_2_cfg_res),
    .io_ptw_pmp_2_cfg_a            (io_ptw_pmp_2_cfg_a),
    .io_ptw_pmp_2_cfg_x            (io_ptw_pmp_2_cfg_x),
    .io_ptw_pmp_2_cfg_w            (io_ptw_pmp_2_cfg_w),
    .io_ptw_pmp_2_cfg_r            (io_ptw_pmp_2_cfg_r),
    .io_ptw_pmp_2_addr             (io_ptw_pmp_2_addr),
    .io_ptw_pmp_2_mask             (io_ptw_pmp_2_mask),
    .io_ptw_pmp_3_cfg_l            (io_ptw_pmp_3_cfg_l),
    .io_ptw_pmp_3_cfg_res          (io_ptw_pmp_3_cfg_res),
    .io_ptw_pmp_3_cfg_a            (io_ptw_pmp_3_cfg_a),
    .io_ptw_pmp_3_cfg_x            (io_ptw_pmp_3_cfg_x),
    .io_ptw_pmp_3_cfg_w            (io_ptw_pmp_3_cfg_w),
    .io_ptw_pmp_3_cfg_r            (io_ptw_pmp_3_cfg_r),
    .io_ptw_pmp_3_addr             (io_ptw_pmp_3_addr),
    .io_ptw_pmp_3_mask             (io_ptw_pmp_3_mask),
    .io_ptw_pmp_4_cfg_l            (io_ptw_pmp_4_cfg_l),
    .io_ptw_pmp_4_cfg_res          (io_ptw_pmp_4_cfg_res),
    .io_ptw_pmp_4_cfg_a            (io_ptw_pmp_4_cfg_a),
    .io_ptw_pmp_4_cfg_x            (io_ptw_pmp_4_cfg_x),
    .io_ptw_pmp_4_cfg_w            (io_ptw_pmp_4_cfg_w),
    .io_ptw_pmp_4_cfg_r            (io_ptw_pmp_4_cfg_r),
    .io_ptw_pmp_4_addr             (io_ptw_pmp_4_addr),
    .io_ptw_pmp_4_mask             (io_ptw_pmp_4_mask),
    .io_ptw_pmp_5_cfg_l            (io_ptw_pmp_5_cfg_l),
    .io_ptw_pmp_5_cfg_res          (io_ptw_pmp_5_cfg_res),
    .io_ptw_pmp_5_cfg_a            (io_ptw_pmp_5_cfg_a),
    .io_ptw_pmp_5_cfg_x            (io_ptw_pmp_5_cfg_x),
    .io_ptw_pmp_5_cfg_w            (io_ptw_pmp_5_cfg_w),
    .io_ptw_pmp_5_cfg_r            (io_ptw_pmp_5_cfg_r),
    .io_ptw_pmp_5_addr             (io_ptw_pmp_5_addr),
    .io_ptw_pmp_5_mask             (io_ptw_pmp_5_mask),
    .io_ptw_pmp_6_cfg_l            (io_ptw_pmp_6_cfg_l),
    .io_ptw_pmp_6_cfg_res          (io_ptw_pmp_6_cfg_res),
    .io_ptw_pmp_6_cfg_a            (io_ptw_pmp_6_cfg_a),
    .io_ptw_pmp_6_cfg_x            (io_ptw_pmp_6_cfg_x),
    .io_ptw_pmp_6_cfg_w            (io_ptw_pmp_6_cfg_w),
    .io_ptw_pmp_6_cfg_r            (io_ptw_pmp_6_cfg_r),
    .io_ptw_pmp_6_addr             (io_ptw_pmp_6_addr),
    .io_ptw_pmp_6_mask             (io_ptw_pmp_6_mask),
    .io_ptw_pmp_7_cfg_l            (io_ptw_pmp_7_cfg_l),
    .io_ptw_pmp_7_cfg_res          (io_ptw_pmp_7_cfg_res),
    .io_ptw_pmp_7_cfg_a            (io_ptw_pmp_7_cfg_a),
    .io_ptw_pmp_7_cfg_x            (io_ptw_pmp_7_cfg_x),
    .io_ptw_pmp_7_cfg_w            (io_ptw_pmp_7_cfg_w),
    .io_ptw_pmp_7_cfg_r            (io_ptw_pmp_7_cfg_r),
    .io_ptw_pmp_7_addr             (io_ptw_pmp_7_addr),
    .io_ptw_pmp_7_mask             (io_ptw_pmp_7_mask),
    .io_kill                       (~s2_valid | s2_kill_speculative_tlb_refill),	// src/main/scala/rocket/Frontend.scala:104:25, :107:58, :156:55, :167:28
    .io_resp_paddr                 (_tlb_io_resp_paddr),
    .io_resp_gpa                   (_tlb_io_resp_gpa),
    .io_resp_pf_ld                 (_tlb_io_resp_pf_ld),
    .io_resp_pf_inst               (_tlb_io_resp_pf_inst),
    .io_resp_ae_ld                 (_tlb_io_resp_ae_ld),
    .io_resp_ae_inst               (_tlb_io_resp_ae_inst),
    .io_resp_ma_ld                 (_tlb_io_resp_ma_ld),
    .io_resp_cacheable             (_tlb_io_resp_cacheable),
    .io_ptw_req_valid              (_tlb_io_ptw_req_valid),
    .io_ptw_req_bits_valid         (io_ptw_req_bits_valid),
    .io_ptw_req_bits_bits_addr     (io_ptw_req_bits_bits_addr),
    .io_ptw_req_bits_bits_need_gpa (io_ptw_req_bits_bits_need_gpa),
    .io_ptw_req_bits_bits_vstage1  (io_ptw_req_bits_bits_vstage1),
    .io_ptw_req_bits_bits_stage2   (io_ptw_req_bits_bits_stage2)
  );
  BTB btb (	// src/main/scala/rocket/Frontend.scala:194:21
    .clock                                     (clock),
    .reset                                     (reset),
    .io_req_bits_addr                          (s1_pc),	// src/main/scala/rocket/Frontend.scala:111:18
    .io_btb_update_valid
      (io_cpu_btb_update_valid
         ? io_cpu_btb_update_valid
         : _T_37 & ~wrong_path & fetch_bubble_likely & updateBTB),	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:122:27, :198:23, :222:32, :313:37, :314:33, :315:{31,52,87}
    .io_btb_update_bits_prediction_cfiType
      (io_cpu_btb_update_bits_prediction_cfiType),
    .io_btb_update_bits_prediction_taken       (io_cpu_btb_update_bits_prediction_taken),
    .io_btb_update_bits_prediction_mask        (io_cpu_btb_update_bits_prediction_mask),
    .io_btb_update_bits_prediction_bridx       (io_cpu_btb_update_bits_prediction_bridx),
    .io_btb_update_bits_prediction_target      (io_cpu_btb_update_bits_prediction_target),
    .io_btb_update_bits_prediction_entry
      (io_cpu_btb_update_valid ? io_cpu_btb_update_bits_prediction_entry : 5'h1C),	// src/main/scala/rocket/Frontend.scala:198:23, :313:37, :316:47
    .io_btb_update_bits_prediction_bht_history
      (io_cpu_btb_update_bits_prediction_bht_history),
    .io_btb_update_bits_prediction_bht_value
      (io_cpu_btb_update_bits_prediction_bht_value),
    .io_btb_update_bits_pc
      (io_cpu_btb_update_valid ? io_cpu_btb_update_bits_pc : s2_base_pc),	// src/main/scala/rocket/Frontend.scala:198:23, :218:22, :313:37, :320:33
    .io_btb_update_bits_target                 (io_cpu_btb_update_bits_target),
    .io_btb_update_bits_isValid
      (~io_cpu_btb_update_valid | io_cpu_btb_update_bits_isValid),	// src/main/scala/rocket/Frontend.scala:198:23, :313:{11,37}, :317:38
    .io_btb_update_bits_br_pc
      (io_cpu_btb_update_valid
         ? io_cpu_btb_update_bits_br_pc
         : {s2_base_pc[31:2], s2_base_pc[1:0] | {taken_idx, 1'h0}}),	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:198:23, :218:22, :219:25, :313:37, :319:{36,50,63}
    .io_btb_update_bits_cfiType
      (io_cpu_btb_update_valid ? io_cpu_btb_update_bits_cfiType : _GEN),	// src/main/scala/rocket/Frontend.scala:198:23, :266:25, :270:40, :313:37, :318:38
    .io_bht_update_valid                       (io_cpu_bht_update_valid),
    .io_bht_update_bits_prediction_history
      (io_cpu_bht_update_bits_prediction_history),
    .io_bht_update_bits_pc                     (io_cpu_bht_update_bits_pc),
    .io_bht_update_bits_branch                 (io_cpu_bht_update_bits_branch),
    .io_bht_update_bits_taken                  (io_cpu_bht_update_bits_taken),
    .io_bht_update_bits_mispredict             (io_cpu_bht_update_bits_mispredict),
    .io_bht_advance_valid
      (~taken_taken & (_taken_T_48 | _taken_T_49)
         ? _T_37 & ~wrong_path
         : (_taken_T_19 | _taken_T_20) & _T_37 & ~wrong_path),	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:122:27, :202:30, :251:71, :255:{53,75}, :266:{13,25}, :269:54, :290:{36,59}, :291:{36,54}
    .io_bht_advance_bits_bht_value             (s2_btb_resp_bits_bht_value),	// src/main/scala/rocket/Frontend.scala:115:29
    .io_ras_update_valid
      (taken_taken
         ? _T_37 & ~wrong_path
           & (taken_prevRVI & (taken_rviCall | taken_rviReturn) | taken_valid
              & (taken_rvcCall | taken_rvcReturn))
         : _T_37 & ~wrong_path
           & (taken_prevRVI_1 & (taken_rviCall_1 | taken_rviReturn_1) | taken_valid_1
              & (taken_rvcCall_1 | taken_rvcReturn_1))),	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/Frontend.scala:122:27, :230:31, :231:44, :238:46, :239:42, :245:29, :247:28, :251:71, :266:25, :269:{33,54,66,78,90,104,113,125}
    .io_ras_update_bits_cfiType                (_GEN),	// src/main/scala/rocket/Frontend.scala:266:25, :270:40
    .io_ras_update_bits_returnAddr             (s2_base_pc + {29'h0, after_idx, 1'h0}),	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/rocket/Frontend.scala:218:22, :220:25, :323:53
    .io_flush                                  (_taken_T_34 | _taken_T_5),	// src/main/scala/rocket/Frontend.scala:257:{88,97}, :260:22
    .io_resp_valid                             (_btb_io_resp_valid),
    .io_resp_bits_cfiType                      (_btb_io_resp_bits_cfiType),
    .io_resp_bits_taken                        (_btb_io_resp_bits_taken),
    .io_resp_bits_mask                         (_btb_io_resp_bits_mask),
    .io_resp_bits_bridx                        (_btb_io_resp_bits_bridx),
    .io_resp_bits_target                       (_btb_io_resp_bits_target),
    .io_resp_bits_entry                        (_btb_io_resp_bits_entry),
    .io_resp_bits_bht_history                  (_btb_io_resp_bits_bht_history),
    .io_resp_bits_bht_value                    (_btb_io_resp_bits_bht_value),
    .io_ras_head_valid                         (_btb_io_ras_head_valid),
    .io_ras_head_bits                          (_btb_io_ras_head_bits)
  );
  assign io_cpu_gpa_valid = gpa_valid;	// src/main/scala/rocket/Frontend.scala:349:22
  assign io_cpu_gpa_bits = gpa;	// src/main/scala/rocket/Frontend.scala:350:16
  assign io_ptw_req_valid = _tlb_io_ptw_req_valid;	// src/main/scala/rocket/Frontend.scala:101:19
endmodule

