// Generated by CIRCT firtool-1.40.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLWidthWidget_3(
  input          clock,
                 reset,
                 auto_in_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [2:0]   auto_in_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_in_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [3:0]   auto_in_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [4:0]   auto_in_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [30:0]  auto_in_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [63:0]  auto_in_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [511:0] auto_in_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input          auto_in_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_in_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [2:0]   auto_out_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [3:0]   auto_out_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [4:0]   auto_out_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input          auto_out_d_bits_denied,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [31:0]  auto_out_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input          auto_out_d_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output         auto_in_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_in_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [2:0]   auto_in_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [3:0]   auto_in_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [4:0]   auto_in_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output         auto_in_d_bits_denied,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [511:0] auto_in_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output         auto_in_d_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [2:0]   auto_out_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [3:0]   auto_out_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [4:0]   auto_out_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [30:0]  auto_out_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output         auto_out_a_bits_user_amba_prot_bufferable,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_bits_user_amba_prot_modifiable,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_bits_user_amba_prot_readalloc,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_bits_user_amba_prot_writealloc,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_bits_user_amba_prot_privileged,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_bits_user_amba_prot_secure,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_a_bits_user_amba_prot_fetch,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [3:0]   auto_out_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [31:0]  auto_out_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output         auto_out_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                 auto_out_d_ready	// src/main/scala/diplomacy/LazyModule.scala:374:18
);

  wire              nodeIn_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [511:0]      _repeated_repeater_io_deq_bits_data;	// src/main/scala/util/Repeater.scala:35:26
  wire              nodeIn_a_valid = auto_in_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]        nodeIn_a_bits_opcode = auto_in_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]        nodeIn_a_bits_param = auto_in_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [3:0]        nodeIn_a_bits_size = auto_in_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [4:0]        nodeIn_a_bits_source = auto_in_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [30:0]       nodeIn_a_bits_address = auto_in_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [63:0]       nodeIn_a_bits_mask = auto_in_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [511:0]      nodeIn_a_bits_data = auto_in_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_a_bits_corrupt = auto_in_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_d_ready = auto_in_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeOut_a_ready = auto_out_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire              nodeOut_d_valid = auto_out_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [2:0]        nodeOut_d_bits_opcode = auto_out_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [3:0]        nodeOut_d_bits_size = auto_out_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [4:0]        nodeOut_d_bits_source = auto_out_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire              nodeOut_d_bits_denied = auto_out_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [31:0]       nodeOut_d_bits_data = auto_out_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire              nodeOut_d_bits_corrupt = auto_out_d_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire              nodeIn_a_bits_user_amba_prot_bufferable = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_a_bits_user_amba_prot_modifiable = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_a_bits_user_amba_prot_readalloc = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_a_bits_user_amba_prot_writealloc = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_a_bits_user_amba_prot_privileged = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_a_bits_user_amba_prot_secure = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_a_bits_user_amba_prot_fetch = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeIn_d_bits_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire              nodeOut_d_bits_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [1:0]        nodeIn_d_bits_param = 2'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]        nodeOut_d_bits_param = 2'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1205:17
  wire              corrupt_out;	// src/main/scala/tilelink/WidthWidget.scala:42:36
  wire              cated_ready = nodeOut_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_valid;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [2:0]        cated_bits_opcode;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [2:0]        cated_bits_param;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [3:0]        cated_bits_size;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [4:0]        cated_bits_source;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [30:0]       cated_bits_address;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_user_amba_prot_bufferable;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_user_amba_prot_modifiable;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_user_amba_prot_readalloc;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_user_amba_prot_writealloc;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_user_amba_prot_privileged;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_user_amba_prot_secure;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_user_amba_prot_fetch;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              cated_bits_corrupt;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [2:0]        nodeIn_d_bits_opcode = nodeOut_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [3:0]        nodeIn_d_bits_size = nodeOut_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [4:0]        nodeIn_d_bits_source = nodeOut_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire              nodeIn_d_bits_denied = nodeOut_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [31:0]       nodeIn_d_bits_data_odata_0 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_1 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_2 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_3 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_4 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_5 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_6 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_7 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_8 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_9 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_10 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_11 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_12 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_13 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_14 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire [31:0]       nodeIn_d_bits_data_odata_15 = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:60:47
  wire              nodeOut_a_valid = cated_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [2:0]        nodeOut_a_bits_opcode = cated_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [2:0]        nodeOut_a_bits_param = cated_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [3:0]        nodeOut_a_bits_size = cated_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [4:0]        nodeOut_a_bits_source = cated_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [30:0]       nodeOut_a_bits_address = cated_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_user_amba_prot_bufferable =
    cated_bits_user_amba_prot_bufferable;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_user_amba_prot_modifiable =
    cated_bits_user_amba_prot_modifiable;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_user_amba_prot_readalloc =
    cated_bits_user_amba_prot_readalloc;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_user_amba_prot_writealloc =
    cated_bits_user_amba_prot_writealloc;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_user_amba_prot_privileged =
    cated_bits_user_amba_prot_privileged;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_user_amba_prot_secure =
    cated_bits_user_amba_prot_secure;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_user_amba_prot_fetch = cated_bits_user_amba_prot_fetch;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire              nodeOut_a_bits_corrupt = cated_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [511:0]      cated_bits_data =
    {_repeated_repeater_io_deq_bits_data[511:32], nodeIn_a_bits_data[31:0]};	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/WidthWidget.scala:156:25, :158:39, :159:37, :160:31, src/main/scala/util/Repeater.scala:35:26
  wire              repeat_hasData = ~(cated_bits_opcode[2]);	// src/main/scala/tilelink/Edges.scala:93:{28,37}, src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [20:0]       _repeat_limit_T_1 = 21'h3F << cated_bits_size;	// src/main/scala/tilelink/WidthWidget.scala:156:25, src/main/scala/util/package.scala:243:71
  wire [3:0]        repeat_limit = ~(_repeat_limit_T_1[5:2]);	// src/main/scala/tilelink/WidthWidget.scala:98:47, src/main/scala/util/package.scala:243:{46,71,76}
  reg  [3:0]        repeat_count;	// src/main/scala/tilelink/WidthWidget.scala:100:26
  wire              repeat_first = repeat_count == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:100:26, :101:25
  wire              repeat_last = repeat_count == repeat_limit | ~repeat_hasData;	// src/main/scala/tilelink/Edges.scala:93:28, src/main/scala/tilelink/WidthWidget.scala:98:47, :100:26, :102:{25,35,38}
  wire [3:0]        repeat_sel = cated_bits_address[5:2];	// src/main/scala/tilelink/WidthWidget.scala:111:39, :156:25
  wire [3:0]        repeat_index = repeat_sel | repeat_count;	// src/main/scala/tilelink/WidthWidget.scala:100:26, :111:39, :121:24
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_0 = cated_bits_data[31:0];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_1 = cated_bits_data[63:32];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_2 = cated_bits_data[95:64];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_3 = cated_bits_data[127:96];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_4 = cated_bits_data[159:128];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_5 = cated_bits_data[191:160];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_6 = cated_bits_data[223:192];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_7 = cated_bits_data[255:224];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_8 = cated_bits_data[287:256];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_9 = cated_bits_data[319:288];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_10 = cated_bits_data[351:320];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_11 = cated_bits_data[383:352];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_12 = cated_bits_data[415:384];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_13 = cated_bits_data[447:416];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_14 = cated_bits_data[479:448];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [31:0]       repeat_nodeOut_a_bits_data_mux_15 = cated_bits_data[511:480];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [15:0][31:0] _GEN =
    {{repeat_nodeOut_a_bits_data_mux_15},
     {repeat_nodeOut_a_bits_data_mux_14},
     {repeat_nodeOut_a_bits_data_mux_13},
     {repeat_nodeOut_a_bits_data_mux_12},
     {repeat_nodeOut_a_bits_data_mux_11},
     {repeat_nodeOut_a_bits_data_mux_10},
     {repeat_nodeOut_a_bits_data_mux_9},
     {repeat_nodeOut_a_bits_data_mux_8},
     {repeat_nodeOut_a_bits_data_mux_7},
     {repeat_nodeOut_a_bits_data_mux_6},
     {repeat_nodeOut_a_bits_data_mux_5},
     {repeat_nodeOut_a_bits_data_mux_4},
     {repeat_nodeOut_a_bits_data_mux_3},
     {repeat_nodeOut_a_bits_data_mux_2},
     {repeat_nodeOut_a_bits_data_mux_1},
     {repeat_nodeOut_a_bits_data_mux_0}};	// src/main/scala/tilelink/WidthWidget.scala:123:43, :132:30
  wire [31:0]       nodeOut_a_bits_data = _GEN[repeat_index];	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:121:24, :132:30
  wire [63:0]       cated_bits_mask;	// src/main/scala/tilelink/WidthWidget.scala:156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_0 = cated_bits_mask[3:0];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_1 = cated_bits_mask[7:4];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_2 = cated_bits_mask[11:8];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_3 = cated_bits_mask[15:12];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_4 = cated_bits_mask[19:16];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_5 = cated_bits_mask[23:20];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_6 = cated_bits_mask[27:24];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_7 = cated_bits_mask[31:28];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_8 = cated_bits_mask[35:32];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_9 = cated_bits_mask[39:36];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_10 = cated_bits_mask[43:40];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_11 = cated_bits_mask[47:44];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_12 = cated_bits_mask[51:48];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_13 = cated_bits_mask[55:52];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_14 = cated_bits_mask[59:56];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [3:0]        repeat_nodeOut_a_bits_mask_mux_15 = cated_bits_mask[63:60];	// src/main/scala/tilelink/WidthWidget.scala:123:{43,55}, :156:25
  wire [15:0][3:0]  _GEN_0 =
    {{repeat_nodeOut_a_bits_mask_mux_15},
     {repeat_nodeOut_a_bits_mask_mux_14},
     {repeat_nodeOut_a_bits_mask_mux_13},
     {repeat_nodeOut_a_bits_mask_mux_12},
     {repeat_nodeOut_a_bits_mask_mux_11},
     {repeat_nodeOut_a_bits_mask_mux_10},
     {repeat_nodeOut_a_bits_mask_mux_9},
     {repeat_nodeOut_a_bits_mask_mux_8},
     {repeat_nodeOut_a_bits_mask_mux_7},
     {repeat_nodeOut_a_bits_mask_mux_6},
     {repeat_nodeOut_a_bits_mask_mux_5},
     {repeat_nodeOut_a_bits_mask_mux_4},
     {repeat_nodeOut_a_bits_mask_mux_3},
     {repeat_nodeOut_a_bits_mask_mux_2},
     {repeat_nodeOut_a_bits_mask_mux_1},
     {repeat_nodeOut_a_bits_mask_mux_0}};	// src/main/scala/tilelink/WidthWidget.scala:123:43, :135:53
  wire [3:0]        nodeOut_a_bits_mask = _GEN_0[repeat_index];	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:121:24, :135:53
  wire              repeat_0 = ~repeat_last;	// src/main/scala/tilelink/WidthWidget.scala:102:35, :143:7, :154:26
  wire              hasData = nodeOut_d_bits_opcode[0];	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/Edges.scala:107:36
  wire [20:0]       _limit_T_1 = 21'h3F << nodeOut_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/util/package.scala:243:71
  wire [3:0]        limit = ~(_limit_T_1[5:2]);	// src/main/scala/tilelink/WidthWidget.scala:33:47, src/main/scala/util/package.scala:243:{46,71,76}
  reg  [3:0]        count;	// src/main/scala/tilelink/WidthWidget.scala:35:27
  wire              first = count == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:35:27, :36:26
  wire              last = count == limit | ~hasData;	// src/main/scala/tilelink/Edges.scala:107:36, src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :37:{26,36,39}
  wire              enable_0 = (count & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,63,72}
  wire              enable_1 = ({count[3:1], ~(count[0])} & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_2 = ({count[3:2], count[1:0] ^ 2'h2} & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_3 = ({count[3:2], ~(count[1:0])} & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_4 = ({count[3], count[2:0] ^ 3'h4} & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_5 = ({count[3], count[2:0] ^ 3'h5} & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_6 = ({count[3], count[2:0] ^ 3'h6} & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_7 = ({count[3], ~(count[2:0])} & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_8 = ((count ^ 4'h8) & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_9 = ((count ^ 4'h9) & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_10 = ((count ^ 4'hA) & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_11 = ((count ^ 4'hB) & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_12 = ((count ^ 4'hC) & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_13 = ((count ^ 4'hD) & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_14 = ((count ^ 4'hE) & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  wire              enable_15 = (~count & limit) == 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:33:47, :35:27, :38:{47,56,63,72}
  reg               corrupt_reg;	// src/main/scala/tilelink/WidthWidget.scala:40:32
  assign corrupt_out = nodeOut_d_bits_corrupt | corrupt_reg;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:40:32, :42:36
  wire              nodeIn_d_bits_corrupt = corrupt_out;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/WidthWidget.scala:42:36
  wire              nodeOut_d_ready = nodeIn_d_ready | ~last;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/WidthWidget.scala:37:36, :71:{29,32}
  wire              nodeIn_d_valid = nodeOut_d_valid & last;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/WidthWidget.scala:37:36, :72:29
  reg               nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:57:41
  wire              nodeIn_d_bits_data_masked_enable_0 =
    enable_0 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_1 =
    enable_1 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_2 =
    enable_2 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_3 =
    enable_3 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_4 =
    enable_4 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_5 =
    enable_5 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_6 =
    enable_6 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_7 =
    enable_7 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_8 =
    enable_8 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_9 =
    enable_9 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_10 =
    enable_10 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_11 =
    enable_11 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_12 =
    enable_12 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_13 =
    enable_13 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_14 =
    enable_14 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  wire              nodeIn_d_bits_data_masked_enable_15 =
    enable_15 | ~nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:38:47, :57:41, :58:{42,45}
  reg  [31:0]       nodeIn_d_bits_data_rdata_0;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_1;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_2;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_3;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_4;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_5;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_6;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_7;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_8;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_9;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_10;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_11;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_12;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_13;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  reg  [31:0]       nodeIn_d_bits_data_rdata_14;	// src/main/scala/tilelink/WidthWidget.scala:61:24
  wire [31:0]       nodeIn_d_bits_data_mdata_0 =
    nodeIn_d_bits_data_masked_enable_0
      ? nodeIn_d_bits_data_odata_0
      : nodeIn_d_bits_data_rdata_0;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_1 =
    nodeIn_d_bits_data_masked_enable_1
      ? nodeIn_d_bits_data_odata_1
      : nodeIn_d_bits_data_rdata_1;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_2 =
    nodeIn_d_bits_data_masked_enable_2
      ? nodeIn_d_bits_data_odata_2
      : nodeIn_d_bits_data_rdata_2;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_3 =
    nodeIn_d_bits_data_masked_enable_3
      ? nodeIn_d_bits_data_odata_3
      : nodeIn_d_bits_data_rdata_3;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_4 =
    nodeIn_d_bits_data_masked_enable_4
      ? nodeIn_d_bits_data_odata_4
      : nodeIn_d_bits_data_rdata_4;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_5 =
    nodeIn_d_bits_data_masked_enable_5
      ? nodeIn_d_bits_data_odata_5
      : nodeIn_d_bits_data_rdata_5;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_6 =
    nodeIn_d_bits_data_masked_enable_6
      ? nodeIn_d_bits_data_odata_6
      : nodeIn_d_bits_data_rdata_6;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_7 =
    nodeIn_d_bits_data_masked_enable_7
      ? nodeIn_d_bits_data_odata_7
      : nodeIn_d_bits_data_rdata_7;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_8 =
    nodeIn_d_bits_data_masked_enable_8
      ? nodeIn_d_bits_data_odata_8
      : nodeIn_d_bits_data_rdata_8;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_9 =
    nodeIn_d_bits_data_masked_enable_9
      ? nodeIn_d_bits_data_odata_9
      : nodeIn_d_bits_data_rdata_9;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_10 =
    nodeIn_d_bits_data_masked_enable_10
      ? nodeIn_d_bits_data_odata_10
      : nodeIn_d_bits_data_rdata_10;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_11 =
    nodeIn_d_bits_data_masked_enable_11
      ? nodeIn_d_bits_data_odata_11
      : nodeIn_d_bits_data_rdata_11;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_12 =
    nodeIn_d_bits_data_masked_enable_12
      ? nodeIn_d_bits_data_odata_12
      : nodeIn_d_bits_data_rdata_12;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_13 =
    nodeIn_d_bits_data_masked_enable_13
      ? nodeIn_d_bits_data_odata_13
      : nodeIn_d_bits_data_rdata_13;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_14 =
    nodeIn_d_bits_data_masked_enable_14
      ? nodeIn_d_bits_data_odata_14
      : nodeIn_d_bits_data_rdata_14;	// src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :61:24, :63:88
  wire [31:0]       nodeIn_d_bits_data_mdata_15 =
    nodeIn_d_bits_data_masked_enable_15
      ? nodeIn_d_bits_data_odata_15
      : nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/WidthWidget.scala:58:42, :60:47, :63:88
  wire [63:0]       nodeIn_d_bits_data_lo_lo_lo =
    {nodeIn_d_bits_data_mdata_1, nodeIn_d_bits_data_mdata_0};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [63:0]       nodeIn_d_bits_data_lo_lo_hi =
    {nodeIn_d_bits_data_mdata_3, nodeIn_d_bits_data_mdata_2};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [127:0]      nodeIn_d_bits_data_lo_lo =
    {nodeIn_d_bits_data_lo_lo_hi, nodeIn_d_bits_data_lo_lo_lo};	// src/main/scala/tilelink/WidthWidget.scala:68:12
  wire [63:0]       nodeIn_d_bits_data_lo_hi_lo =
    {nodeIn_d_bits_data_mdata_5, nodeIn_d_bits_data_mdata_4};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [63:0]       nodeIn_d_bits_data_lo_hi_hi =
    {nodeIn_d_bits_data_mdata_7, nodeIn_d_bits_data_mdata_6};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [127:0]      nodeIn_d_bits_data_lo_hi =
    {nodeIn_d_bits_data_lo_hi_hi, nodeIn_d_bits_data_lo_hi_lo};	// src/main/scala/tilelink/WidthWidget.scala:68:12
  wire [255:0]      nodeIn_d_bits_data_lo =
    {nodeIn_d_bits_data_lo_hi, nodeIn_d_bits_data_lo_lo};	// src/main/scala/tilelink/WidthWidget.scala:68:12
  wire [63:0]       nodeIn_d_bits_data_hi_lo_lo =
    {nodeIn_d_bits_data_mdata_9, nodeIn_d_bits_data_mdata_8};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [63:0]       nodeIn_d_bits_data_hi_lo_hi =
    {nodeIn_d_bits_data_mdata_11, nodeIn_d_bits_data_mdata_10};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [127:0]      nodeIn_d_bits_data_hi_lo =
    {nodeIn_d_bits_data_hi_lo_hi, nodeIn_d_bits_data_hi_lo_lo};	// src/main/scala/tilelink/WidthWidget.scala:68:12
  wire [63:0]       nodeIn_d_bits_data_hi_hi_lo =
    {nodeIn_d_bits_data_mdata_13, nodeIn_d_bits_data_mdata_12};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [63:0]       nodeIn_d_bits_data_hi_hi_hi =
    {nodeIn_d_bits_data_mdata_15, nodeIn_d_bits_data_mdata_14};	// src/main/scala/tilelink/WidthWidget.scala:63:88, :68:12
  wire [127:0]      nodeIn_d_bits_data_hi_hi =
    {nodeIn_d_bits_data_hi_hi_hi, nodeIn_d_bits_data_hi_hi_lo};	// src/main/scala/tilelink/WidthWidget.scala:68:12
  wire [255:0]      nodeIn_d_bits_data_hi =
    {nodeIn_d_bits_data_hi_hi, nodeIn_d_bits_data_hi_lo};	// src/main/scala/tilelink/WidthWidget.scala:68:12
  wire [511:0]      nodeIn_d_bits_data = {nodeIn_d_bits_data_hi, nodeIn_d_bits_data_lo};	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/WidthWidget.scala:68:12
  always @(posedge clock) begin
    automatic logic _nodeIn_d_bits_data_T;	// src/main/scala/chisel3/util/Decoupled.scala:52:35
    automatic logic _nodeIn_d_bits_data_T_2;	// src/main/scala/tilelink/WidthWidget.scala:64:23
    _nodeIn_d_bits_data_T = nodeOut_d_ready & nodeOut_d_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Nodes.scala:1205:17
    _nodeIn_d_bits_data_T_2 = _nodeIn_d_bits_data_T & ~last;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/tilelink/WidthWidget.scala:37:36, :64:23, :71:32
    if (reset) begin
      repeat_count <= 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:100:26
      count <= 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:35:27
      corrupt_reg <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/tilelink/WidthWidget.scala:40:32
      nodeIn_d_bits_data_rdata_written_once <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/tilelink/WidthWidget.scala:57:41
    end
    else begin
      if (nodeOut_a_ready & nodeOut_a_valid) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Nodes.scala:1205:17
        if (repeat_last)	// src/main/scala/tilelink/WidthWidget.scala:102:35
          repeat_count <= 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:100:26
        else	// src/main/scala/tilelink/WidthWidget.scala:102:35
          repeat_count <= repeat_count + 4'h1;	// src/main/scala/tilelink/WidthWidget.scala:100:26, :105:24
      end
      if (_nodeIn_d_bits_data_T) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35
        if (last)	// src/main/scala/tilelink/WidthWidget.scala:37:36
          count <= 4'h0;	// src/main/scala/tilelink/WidthWidget.scala:35:27
        else	// src/main/scala/tilelink/WidthWidget.scala:37:36
          count <= count + 4'h1;	// src/main/scala/tilelink/WidthWidget.scala:35:27, :45:24
        corrupt_reg <= ~last & corrupt_out;	// src/main/scala/tilelink/WidthWidget.scala:37:36, :40:32, :42:36, :46:21, :47:21, :49:23
      end
      nodeIn_d_bits_data_rdata_written_once <=
        _nodeIn_d_bits_data_T_2 | nodeIn_d_bits_data_rdata_written_once;	// src/main/scala/tilelink/WidthWidget.scala:57:41, :64:{23,33}, :65:30
    end
    if (_nodeIn_d_bits_data_T_2) begin	// src/main/scala/tilelink/WidthWidget.scala:64:23
      nodeIn_d_bits_data_rdata_0 <= nodeIn_d_bits_data_mdata_0;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_1 <= nodeIn_d_bits_data_mdata_1;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_2 <= nodeIn_d_bits_data_mdata_2;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_3 <= nodeIn_d_bits_data_mdata_3;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_4 <= nodeIn_d_bits_data_mdata_4;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_5 <= nodeIn_d_bits_data_mdata_5;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_6 <= nodeIn_d_bits_data_mdata_6;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_7 <= nodeIn_d_bits_data_mdata_7;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_8 <= nodeIn_d_bits_data_mdata_8;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_9 <= nodeIn_d_bits_data_mdata_9;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_10 <= nodeIn_d_bits_data_mdata_10;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_11 <= nodeIn_d_bits_data_mdata_11;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_12 <= nodeIn_d_bits_data_mdata_12;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_13 <= nodeIn_d_bits_data_mdata_13;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
      nodeIn_d_bits_data_rdata_14 <= nodeIn_d_bits_data_mdata_14;	// src/main/scala/tilelink/WidthWidget.scala:61:24, :63:88
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:15];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM[i[3:0]] = `RANDOM;
        end
        repeat_count = _RANDOM[4'h0][3:0];	// src/main/scala/tilelink/WidthWidget.scala:100:26
        count = _RANDOM[4'h0][7:4];	// src/main/scala/tilelink/WidthWidget.scala:35:27, :100:26
        corrupt_reg = _RANDOM[4'h0][8];	// src/main/scala/tilelink/WidthWidget.scala:40:32, :100:26
        nodeIn_d_bits_data_rdata_written_once = _RANDOM[4'h0][9];	// src/main/scala/tilelink/WidthWidget.scala:57:41, :100:26
        nodeIn_d_bits_data_rdata_0 = {_RANDOM[4'h0][31:10], _RANDOM[4'h1][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24, :100:26
        nodeIn_d_bits_data_rdata_1 = {_RANDOM[4'h1][31:10], _RANDOM[4'h2][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_2 = {_RANDOM[4'h2][31:10], _RANDOM[4'h3][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_3 = {_RANDOM[4'h3][31:10], _RANDOM[4'h4][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_4 = {_RANDOM[4'h4][31:10], _RANDOM[4'h5][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_5 = {_RANDOM[4'h5][31:10], _RANDOM[4'h6][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_6 = {_RANDOM[4'h6][31:10], _RANDOM[4'h7][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_7 = {_RANDOM[4'h7][31:10], _RANDOM[4'h8][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_8 = {_RANDOM[4'h8][31:10], _RANDOM[4'h9][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_9 = {_RANDOM[4'h9][31:10], _RANDOM[4'hA][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_10 = {_RANDOM[4'hA][31:10], _RANDOM[4'hB][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_11 = {_RANDOM[4'hB][31:10], _RANDOM[4'hC][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_12 = {_RANDOM[4'hC][31:10], _RANDOM[4'hD][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_13 = {_RANDOM[4'hD][31:10], _RANDOM[4'hE][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
        nodeIn_d_bits_data_rdata_14 = {_RANDOM[4'hE][31:10], _RANDOM[4'hF][9:0]};	// src/main/scala/tilelink/WidthWidget.scala:61:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  Repeater_4 repeated_repeater (	// src/main/scala/util/Repeater.scala:35:26
    .clock                                 (clock),
    .reset                                 (reset),
    .io_repeat                             (repeat_0),	// src/main/scala/tilelink/WidthWidget.scala:154:26
    .io_enq_valid                          (nodeIn_a_valid),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_opcode                    (nodeIn_a_bits_opcode),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_param                     (nodeIn_a_bits_param),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_size                      (nodeIn_a_bits_size),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_source                    (nodeIn_a_bits_source),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_address                   (nodeIn_a_bits_address),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_mask                      (nodeIn_a_bits_mask),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_data                      (nodeIn_a_bits_data),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_enq_bits_corrupt                   (nodeIn_a_bits_corrupt),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_deq_ready                          (cated_ready),	// src/main/scala/tilelink/WidthWidget.scala:156:25
    .io_enq_ready                          (nodeIn_a_ready),
    .io_deq_valid                          (cated_valid),
    .io_deq_bits_opcode                    (cated_bits_opcode),
    .io_deq_bits_param                     (cated_bits_param),
    .io_deq_bits_size                      (cated_bits_size),
    .io_deq_bits_source                    (cated_bits_source),
    .io_deq_bits_address                   (cated_bits_address),
    .io_deq_bits_user_amba_prot_bufferable (cated_bits_user_amba_prot_bufferable),
    .io_deq_bits_user_amba_prot_modifiable (cated_bits_user_amba_prot_modifiable),
    .io_deq_bits_user_amba_prot_readalloc  (cated_bits_user_amba_prot_readalloc),
    .io_deq_bits_user_amba_prot_writealloc (cated_bits_user_amba_prot_writealloc),
    .io_deq_bits_user_amba_prot_privileged (cated_bits_user_amba_prot_privileged),
    .io_deq_bits_user_amba_prot_secure     (cated_bits_user_amba_prot_secure),
    .io_deq_bits_user_amba_prot_fetch      (cated_bits_user_amba_prot_fetch),
    .io_deq_bits_mask                      (cated_bits_mask),
    .io_deq_bits_data                      (_repeated_repeater_io_deq_bits_data),
    .io_deq_bits_corrupt                   (cated_bits_corrupt)
  );
  assign auto_in_a_ready = nodeIn_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_valid = nodeIn_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_size = nodeIn_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_source = nodeIn_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_denied = nodeIn_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_data = nodeIn_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_corrupt = nodeIn_d_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_out_a_valid = nodeOut_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_opcode = nodeOut_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_param = nodeOut_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_size = nodeOut_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_source = nodeOut_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_address = nodeOut_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_user_amba_prot_bufferable =
    nodeOut_a_bits_user_amba_prot_bufferable;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_user_amba_prot_modifiable =
    nodeOut_a_bits_user_amba_prot_modifiable;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_user_amba_prot_readalloc =
    nodeOut_a_bits_user_amba_prot_readalloc;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_user_amba_prot_writealloc =
    nodeOut_a_bits_user_amba_prot_writealloc;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_user_amba_prot_privileged =
    nodeOut_a_bits_user_amba_prot_privileged;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_user_amba_prot_secure = nodeOut_a_bits_user_amba_prot_secure;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_user_amba_prot_fetch = nodeOut_a_bits_user_amba_prot_fetch;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_mask = nodeOut_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_data = nodeOut_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_corrupt = nodeOut_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_d_ready = nodeOut_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
endmodule

