// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef _VLSIM__SYMS_H_
#define _VLSIM__SYMS_H_  // guard

#include "verilated_heavy.h"

// INCLUDE MODULE CLASSES
#include "vlsim.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS
class vlsim__Syms : public VerilatedSyms {
  public:
    
    // LOCAL STATE
    const char* __Vm_namep;
    bool __Vm_didInit;
    
    // SUBCELL STATE
    vlsim*                         TOPp;
    
    // SCOPE NAMES
    VerilatedScope __Vscope_mkXsimTop;
    VerilatedScope __Vscope_mkXsimTop__lMMUIndicationOutputNoc_fifoMsgSource;
    VerilatedScope __Vscope_mkXsimTop__lMMUIndicationOutputNoc_fifoMsgSource__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInputNoc_fifoMsgSink;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInputNoc_fifoMsgSink__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__idRequest_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__idRequest_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__idReturn_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__idReturn_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__region_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__region_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__setInterface_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__setInterface_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__sglist_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMMURequestInput__sglist_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__configResponseFifo;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__configResponseFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__dmaErrorFifo;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__dmaErrorFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__dmaErrorFifos_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__dmaErrorFifos_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__dmaErrorFifos_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__dmaErrorFifos_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__idResponseFifo;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__idResponseFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__idReturnFifo;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__idReturnFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__incomingReqs_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__incomingReqs_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__incomingReqs_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__incomingReqs_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__offs1_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__offs1_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__offs1_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__offs1_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__pageResponseFifos_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__pageResponseFifos_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__pageResponseFifos_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__pageResponseFifos_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__regall_cbram_responseFifo_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__regall_cbram_responseFifo_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__regall_cbram_responseFifo_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__regall_cbram_responseFifo_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__reqs0_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__reqs0_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__reqs0_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__reqs0_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__sglId_gen_comp_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__sglId_gen_comp_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__sglId_gen_retFifo;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__sglId_gen_retFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__sglId_gen_tagFifo;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__sglId_gen_tagFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage3Params_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage3Params_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage3Params_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage3Params_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage4Params_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage4Params_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage4Params_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__stage4Params_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__translationTable_cbram_responseFifo_0;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__translationTable_cbram_responseFifo_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__translationTable_cbram_responseFifo_1;
    VerilatedScope __Vscope_mkXsimTop__lMMU_mmu__translationTable_cbram_responseFifo_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServerIndicationOutputNoc_fifoMsgSource;
    VerilatedScope __Vscope_mkXsimTop__lMemServerIndicationOutputNoc_fifoMsgSource__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInputNoc_fifoMsgSink;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInputNoc_fifoMsgSink__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__addrTrans_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__addrTrans_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__memoryTraffic_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__memoryTraffic_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__setTileState_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__setTileState_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__stateDbg_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServerRequestInput__stateDbg_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_addrReqFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_addrReqFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_mmu_servers_0_tokFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_mmu_servers_0_tokFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientData_serverAdapterA_outDataCore;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientData_serverAdapterA_outDataCore__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientData_serverAdapterB_outDataCore;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientData_serverAdapterB_outDataCore__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientRequest;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientRequest__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientSelect;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_clientSelect__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_dmaErrorFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_dmaErrorFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverData;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverData__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverProcessing_serverAdapterA_outDataCore;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverProcessing_serverAdapterA_outDataCore__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverProcessing_serverAdapterB_outDataCore;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverProcessing_serverAdapterB_outDataCore__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverRequest;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverRequest__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverTag;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_serverTag__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_tag_gen_comp_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_tag_gen_comp_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_tag_gen_retFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_tag_gen_retFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_tag_gen_tagFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_reader_readers_0_tag_gen_tagFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_addrReqFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_addrReqFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_mmu_servers_0_tokFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_mmu_servers_0_tokFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientRequest;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientRequest__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientResponse;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientResponse__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientWriteData_0;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientWriteData_0__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientWriteData_1;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_clientWriteData_1__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_dmaErrorFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_dmaErrorFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_memDataFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_memDataFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_respFifos_serverAdapterA_outDataCore;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_respFifos_serverAdapterA_outDataCore__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_respFifos_serverAdapterB_outDataCore;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_respFifos_serverAdapterB_outDataCore__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_serverProcessing;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_serverProcessing__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_serverRequest;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_serverRequest__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_tag_gen_comp_fifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_tag_gen_comp_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_tag_gen_retFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_tag_gen_retFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_tag_gen_tagFifo;
    VerilatedScope __Vscope_mkXsimTop__lMemServer_writer_writers_0_tag_gen_tagFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_bFifo;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_bFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_readDelayFifo;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_readDelayFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_taglastfifo;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_taglastfifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_writeDelayFifo;
    VerilatedScope __Vscope_mkXsimTop__slave_2_0_writeDelayFifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__top__lFromHostInputNoc_fifoMsgSink;
    VerilatedScope __Vscope_mkXsimTop__top__lFromHostInputNoc_fifoMsgSink__error_checks;
    VerilatedScope __Vscope_mkXsimTop__top__lFromHostInput__startPC_requestAdapter_fifo;
    VerilatedScope __Vscope_mkXsimTop__top__lFromHostInput__startPC_requestAdapter_fifo__error_checks;
    VerilatedScope __Vscope_mkXsimTop__top__lToHostOutputNoc_fifoMsgSource;
    VerilatedScope __Vscope_mkXsimTop__top__lToHostOutputNoc_fifoMsgSource__error_checks;
    
    // CREATORS
    vlsim__Syms(vlsim* topp, const char* namep);
    ~vlsim__Syms() {}
    
    // METHODS
    inline const char* name() { return __Vm_namep; }
    
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
