
GENERATED_CPP=GeneratedCppCallbacks.cpp MemServerRequest.c MemServerRequestJson.cpp MMURequest.c MMURequestJson.cpp MemServerIndication.c MemServerIndicationJson.cpp MMUIndication.c MMUIndicationJson.cpp XsimMsgRequest.c XsimMsgRequestJson.cpp XsimMsgIndication.c XsimMsgIndicationJson.cpp FromHost.c FromHostJson.cpp ToHost.c ToHostJson.cpp
